import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import type { WorkshopInventory } from "@/lib/dal/workshop-inventory";

const PAGE = { width: 841.89, height: 595.28, margin: 38 };
const teal = rgb(0, 0.43, 0.43); const ink = rgb(0.08, 0.18, 0.17); const muted = rgb(0.39, 0.48, 0.46); const line = rgb(0.82, 0.88, 0.86); const pale = rgb(0.96, 0.98, 0.97);
const ascii = (value: string | null | undefined) => (value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^\x20-\x7E]/g, "-");
function clip(value: string, font: PDFFont, size: number, width: number) { let result = ascii(value); while (result && font.widthOfTextAtSize(result, size) > width) result = result.slice(0, -1); return result.length < ascii(value).length ? `${result.slice(0, -3)}...` : result; }

export async function createInventoryStocktakePdf(inventory: WorkshopInventory) {
  const document = await PDFDocument.create();
  document.setTitle(`${ascii(inventory.workshopName)} stocktake sheet`); document.setAuthor("pitster"); document.setCreator("pitster");
  const regular = await document.embedFont(StandardFonts.Helvetica); const bold = await document.embedFont(StandardFonts.HelveticaBold);
  const pages: PDFPage[] = []; let page!: PDFPage; let y = 0;
  const columns = [
    { label: "SKU", x: 38, width: 70 }, { label: "ITEM", x: 112, width: 182 },
    { label: "BIN", x: 298, width: 76 }, { label: "SYSTEM", x: 378, width: 65 },
    { label: "COUNTED", x: 447, width: 72 }, { label: "VARIANCE", x: 523, width: 72 },
    { label: "NOTES", x: 599, width: 204 },
  ];
  const addPage = () => {
    page = document.addPage([PAGE.width, PAGE.height]); pages.push(page); y = PAGE.height - PAGE.margin;
    page.drawText("pitster", { x: PAGE.margin, y, size: 18, font: bold, color: teal });
    page.drawText("INVENTORY STOCKTAKE", { x: 665, y: y + 3, size: 9, font: bold, color: muted }); y -= 28;
    page.drawText(ascii(inventory.workshopName), { x: PAGE.margin, y, size: 17, font: bold, color: ink });
    page.drawText(`Organisation: ${ascii(inventory.serviceProviderName)}`, { x: PAGE.margin, y: y - 15, size: 8, font: regular, color: muted });
    page.drawText(`Date: ____________________   Counted by: ______________________________`, { x: 470, y: y - 6, size: 8, font: regular, color: muted }); y -= 38;
    page.drawRectangle({ x: PAGE.margin, y: y - 18, width: PAGE.width - PAGE.margin * 2, height: 22, color: pale });
    for (const column of columns) page.drawText(column.label, { x: column.x + 3, y: y - 11, size: 7, font: bold, color: muted }); y -= 22;
  };
  addPage();
  for (const item of inventory.items) {
    if (y < PAGE.margin + 38) addPage();
    const height = 27; page.drawLine({ start: { x: PAGE.margin, y: y - height }, end: { x: PAGE.width - PAGE.margin, y: y - height }, thickness: .7, color: line });
    const values = [item.sku, item.itemName, item.storageLocation ?? "-", `${item.quantity} ${item.unit}`, "", "", ""];
    values.forEach((value, index) => page.drawText(clip(value, regular, 8, columns[index].width - 6), { x: columns[index].x + 3, y: y - 17, size: 8, font: index < 2 ? bold : regular, color: ink }));
    for (const x of columns.slice(1).map((column) => column.x)) page.drawLine({ start: { x, y: y + 4 }, end: { x, y: y - height }, thickness: .35, color: line });
    y -= height;
  }
  if (!inventory.items.length) { page.drawText("No inventory items recorded.", { x: PAGE.margin, y: y - 20, size: 10, font: regular, color: muted }); }
  pages.forEach((item, index) => item.drawText(`Generated by pitster  |  ${inventory.items.length} items  |  Page ${index + 1} of ${pages.length}`, { x: PAGE.margin, y: 20, size: 7, font: regular, color: muted }));
  return document.save();
}
