import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const migration = await readFile(
  new URL("../supabase/migrations/202607290001_phase_2b1_foundation.sql", import.meta.url),
  "utf8",
);
const doctorDal = await readFile(
  new URL("../lib/dal/doctor.ts", import.meta.url),
  "utf8",
);

test("RLS is enabled on every application table", () => {
  const tables = [
    "clinicians", "patients", "allergies", "medications",
    "chronic_conditions", "surgeries", "implants_and_devices",
    "emergency_contacts", "patient_access_grants", "audit_events",
  ];
  for (const table of tables) {
    assert.match(migration, new RegExp(`alter table public\\.${table} enable row level security`, "i"), table);
  }
});

test("clinical writes require edit grants and patients have no clinical update policy", () => {
  for (const table of [
    "allergies", "medications", "chronic_conditions",
    "surgeries", "implants_and_devices", "emergency_contacts",
  ]) {
    assert.match(
      migration,
      new RegExp(`policy [^\\n]+ on public\\.${table} for update to authenticated[\\s\\S]{0,180}has_patient_access\\(patient_id, true\\)`, "i"),
      table,
    );
  }
  assert.doesNotMatch(migration, /create policy .* on public\.patients for update/i);
  assert.doesNotMatch(migration, /policy\s+\S*patient\S*\s+on public\.(?:allergies|medications|chronic_conditions|surgeries|implants_and_devices)\s+for update/i);
});

test("anonymous access is revoked and all policies target authenticated users", () => {
  assert.match(migration, /revoke all on all tables in schema public from anon, authenticated/i);
  assert.doesNotMatch(migration, /create policy[\s\S]{0,200}\bto anon\b/i);
});

test("authenticated table privileges are allowlisted and cannot bypass RLS with truncate", () => {
  assert.match(migration, /revoke all on all tables in schema public from anon, authenticated/i);
  for (const table of ["clinicians", "patient_access_grants", "audit_events"]) {
    assert.match(migration, new RegExp(`grant select on public\\.${table} to authenticated`, "i"));
  }
  assert.doesNotMatch(migration, /grant\s+(?:all|truncate|insert|update|delete)\b[^;]*\bto authenticated/i);
});

test("audit rows are immutable and cannot be directly mutated", () => {
  assert.match(migration, /before update or delete on public\.audit_events/i);
  assert.match(migration, /revoke all on all tables in schema public from anon, authenticated/i);
  assert.doesNotMatch(migration, /create policy .* on public\.audit_events for insert/i);
});

test("audit metadata records field names and never clinical values", () => {
  assert.match(migration, /"changed_fields":\["clinical_note"\]/);
  const auditInsertMetadata = [...migration.matchAll(/safe_metadata[\s\S]{0,400}?(\{[^;]*\})/gi)]
    .map((match) => match[1])
    .join("\n");
  for (const forbidden of ["password", "token", "cookie", "before_record", "after_record"]) {
    assert.equal(auditInsertMetadata.toLowerCase().includes(forbidden), false, forbidden);
  }
});

test("required audit actions are constrained and generated by secure operations", () => {
  for (const action of [
    "sign_in", "sign_out", "access_denied", "patient_profile_viewed",
    "patient_profile_updated", "access_grant_created",
    "access_grant_approved", "access_grant_revoked",
  ]) {
    assert.equal(migration.includes(`'${action}'`), true, action);
  }
  assert.match(migration, /security definer[\s\S]+patient_profile_viewed/i);
  assert.match(migration, /trigger patient_access_grants_audit/i);
});

test("denied profile reads commit an audit event instead of raising a rollback", () => {
  const deniedBranch = migration.match(
    /if clinician_id is null or not public\.has_patient_access[\s\S]+?return null;\s+end if;/i,
  )?.[0] ?? "";
  assert.match(deniedBranch, /'access_denied'/i);
  assert.match(deniedBranch, /return null/i);
  assert.doesNotMatch(deniedBranch, /raise/i);
});

test("dashboard medical reads go through the audited profile function", () => {
  assert.match(doctorDal, /rpc\("get_patient_profile"/);
  for (const table of ["patients", "chronic_conditions", "allergies", "medications"]) {
    assert.doesNotMatch(doctorDal, new RegExp(`\\.from\\("${table}"\\)`), table);
  }
});
