import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read = (path) => readFile(path, "utf8");
const migration = await read("supabase/migrations/202608130055_workshop_capacity_vehicle_service_history.sql");
const dedicatedMigration = await read("supabase/migrations/202608210072_dedicated_workshop_capacity_resources.sql");
const calendar = await read("app/workshop-manager/requests/WorkshopBookingCalendar.tsx");
const capacity = await read("app/workshop-manager/capacity/CapacityResourcesClient.tsx");
const history = await read("app/garage/[vehicleId]/VehicleServiceHistoryClient.tsx");
const pdf = await read("lib/pdf/vehicle-service-history.ts");
const publicBooking = await read("app/workshops/[workshopId]/request/ServiceRequestFlow.tsx");

test("calendar resources are location scoped, RPC managed, and overlap protected", () => {
  for (const table of ["workshop_schedule_resources", "workshop_resource_absences", "service_booking_resource_assignments"]) {
    assert.match(migration, new RegExp(`create table public\\.${table}`));
    assert.match(migration, new RegExp(`alter table public\\.${table} enable row level security`));
  }
  assert.match(migration, /private\.can_manage_automotive_workshop/);
  assert.match(migration, /tstzrange\(other\.confirmed_start/);
  assert.match(migration, /raise exception 'The selected resource is already occupied'/);
});

test("calendar keeps scheduling warnings and drag rescheduling while resource setup is dedicated", () => {
  for (const view of ["agenda", "day", "week", "month"]) assert.match(calendar, new RegExp(`"${view}"`));
  assert.match(calendar, /draggable=\{booking\.status === "confirmed"\}/);
  assert.match(calendar, /text\/pitster-booking/);
  assert.match(calendar, /capacity\.warning\.daily/);
  assert.match(calendar, /capacity\.warning\.closure/);
  assert.doesNotMatch(calendar, /<WorkshopCapacityPanel/);
  assert.match(calendar, /locationName/);
  assert.match(capacity, /application\/x-pitster-personnel/);
  assert.match(capacity, /addCapacityAbsenceAction/);
  assert.match(dedicatedMigration, /resource_category in \('personnel', 'workstation'\)/);
});

test("VIN stays optional and completed bookings anchor portable service history", () => {
  assert.match(publicBooking, /VIN \(optional\)/);
  assert.doesNotMatch(publicBooking, /name="vehicleVin"[^>]+required/);
  assert.match(migration, /vehicle_vin text check/);
  assert.match(migration, /create table public\.vehicle_service_records/);
  assert.match(migration, /create table public\.vehicle_service_record_parts/);
  assert.match(migration, /create table public\.vehicle_maintenance_recommendations/);
  assert.match(migration, /service_booking_completed_record/);
});

test("customers receive a vehicle timeline and authenticated downloadable PDF", () => {
  assert.match(history, /serviceHistory\.upcoming/);
  assert.match(history, /serviceHistory\.warrantyUntil/);
  assert.match(history, /\/api\/vehicles\/\$\{vehicle\.id\}\/service-history/);
  assert.match(pdf, /PDFDocument\.create/);
  assert.match(pdf, /Parts installed and warranty/);
  assert.match(pdf, /Maintenance recommendations/);
  assert.match(pdf, /Generated by pitster/);
});
