import type { Language } from "@/app/i18n";
import type { GuidanceRole } from "@/lib/dal/guidance";

export type GuidanceCopy = {
  title: string;
  purpose: string;
  why: string;
  steps: string[];
  action: string;
};

export type GuidanceDefinition = GuidanceCopy & {
  key: string;
  version: number;
  href: string;
};

export const guidanceUi: Record<Language, {
  eyebrow: string; open: string; dismiss: string; why: string; steps: string;
  close: string; help: string; tooltip: string;
}> = {
  en: { eyebrow: "About this page", open: "View guidance", dismiss: "Dismiss introduction", why: "Why this matters", steps: "Recommended steps", close: "Close guidance", help: "Help and guidance", tooltip: "Why this page matters" },
  de: { eyebrow: "Über diese Seite", open: "Anleitung anzeigen", dismiss: "Einführung ausblenden", why: "Warum das wichtig ist", steps: "Empfohlene Schritte", close: "Anleitung schließen", help: "Hilfe und Anleitung", tooltip: "Warum diese Seite wichtig ist" },
  ro: { eyebrow: "Despre această pagină", open: "Vezi îndrumarea", dismiss: "Ascunde introducerea", why: "De ce este important", steps: "Pași recomandați", close: "Închide îndrumarea", help: "Ajutor și îndrumare", tooltip: "De ce este importantă această pagină" },
  hu: { eyebrow: "Az oldalról", open: "Útmutató megnyitása", dismiss: "Bevezető elrejtése", why: "Miért fontos", steps: "Javasolt lépések", close: "Útmutató bezárása", help: "Súgó és útmutató", tooltip: "Miért fontos ez az oldal" },
};

type CopyId = "managerOverview" | "organisationOverview" | "requests" | "capacity" | "repairs" | "quality" | "profile" | "services" | "inventory" | "locations" | "managers" | "billing" | "customerInvoicing";

const copy: Record<Language, Record<CopyId, GuidanceCopy>> = {
  en: {
    managerOverview: { title: "Your workshop overview", purpose: "Use this page to see workshop access, operational alerts and the areas that still need attention.", why: "Complete workshop information and operational settings help customers find you and help the team avoid preventable booking problems.", steps: ["Complete the public workshop profile.", "Publish the services customers can request.", "Configure capacity, resources and essential inventory."], action: "Open workshop settings" },
    organisationOverview: { title: "Your organisation overview", purpose: "Compare locations, current workload, quality signals and operational exceptions from one place.", why: "Consistent setup across locations improves visibility and makes capacity, stock and service gaps easier to identify.", steps: ["Check that every location has a manager and billing coverage.", "Compare service and capacity setup between locations.", "Review inventory and quality alerts regularly."], action: "Manage locations" },
    requests: { title: "Requests and workshop calendar", purpose: "Review customer requests, create appointments and schedule accepted work for the selected location.", why: "A location-specific calendar prevents teams from editing the wrong workshop schedule.", steps: ["Select the workshop location.", "Review new requests before confirming appointments.", "Assign accepted work to available personnel and workstations."], action: "Open workshop calendar" },
    capacity: { title: "Capacity and resources", purpose: "Manage each location’s personnel, physical workstations, daily capacity and availability.", why: "Clear personnel-to-workstation assignments make usable capacity visible and reduce scheduling conflicts.", steps: ["Add personnel and their specialties.", "Add bays, ramps, lifts and other workstations.", "Drag personnel to workstations and record absences or maintenance."], action: "Manage capacity" },
    repairs: { title: "Repair lifecycle", purpose: "Move accepted work through diagnosis, estimate, approval, repair and collection while keeping a clear service record.", why: "Consistent status updates reduce missed work, clarify responsibility and keep customer notifications accurate.", steps: ["Open the service order before work begins.", "Record diagnosis and request approval where required.", "Complete the service record before vehicle collection."], action: "Review active repairs" },
    quality: { title: "Quality, warranties and reminders", purpose: "Track warranty cases, repeat repairs and maintenance reminders across the workshops you manage.", why: "Recording quality issues consistently helps identify recurring causes and protect customer trust.", steps: ["Review open warranty and comeback cases.", "Record the outcome and corrective action.", "Follow up on due maintenance reminders."], action: "Review quality items" },
    profile: { title: "Workshop profile and booking rules", purpose: "Manage the information customers see and the rules Pitster uses when offering appointment dates.", why: "A complete profile, logo, accurate location and realistic booking rules improve trust and visibility.", steps: ["Add a logo, description and public contact details.", "Confirm the exact map location and opening hours.", "Set realistic lead time, horizon and daily capacity."], action: "Complete workshop profile" },
    services: { title: "Service catalogue", purpose: "Publish the services customers can request from each workshop, including duration, price guidance and booking mode.", why: "Pitster recommends workshops by matching the customer’s selected service to active catalogue entries.", steps: ["Publish the workshop’s core services first.", "Add realistic duration and starting-price information.", "Review the catalogue when equipment or skills change."], action: "Add or review services" },
    inventory: { title: "Parts and consumables inventory", purpose: "Track frequently used stock, movements and reorder levels for each workshop.", why: "Useful reorder levels reveal shortages early and reduce repair delays caused by missing parts or consumables.", steps: ["Start with oils, filters, brakes and common consumables.", "Set a minimum quantity for important items.", "Record receipts, usage and stocktakes consistently."], action: "Open inventory" },
    locations: { title: "Workshop locations", purpose: "Add, claim and configure the physical locations operated by your service organisation.", why: "Every location needs accurate public information, an assigned manager and active coverage before it can operate effectively.", steps: ["Confirm the address and public profile.", "Assign the responsible workshop manager.", "Complete services, capacity and billing coverage."], action: "Review locations" },
    managers: { title: "Workshop managers", purpose: "Invite managers and control which location each person is responsible for.", why: "Clear location assignments protect workshop data and ensure operational tasks reach the correct manager.", steps: ["Invite the manager using their work email.", "Assign the correct workshop location.", "Remove access promptly when responsibilities change."], action: "Manage access" },
    billing: { title: "Subscription and billing", purpose: "Review organisation coverage, subscription status, invoices and upcoming workshop charges.", why: "Billing coverage determines which locations have continued access to the organisation’s operational tools.", steps: ["Confirm company and invoicing information.", "Review coverage for every active location.", "Resolve payment or subscription warnings before access is affected."], action: "Review billing" },
    customerInvoicing: { title: "Customer invoicing preference", purpose: "Choose whether Pitster records customer invoice details or your workshop keeps invoicing entirely in local software.", why: "A clear setting avoids duplicate invoice entry without removing estimates, repair records or service history.", steps: ["Choose the organisation default.", "Override only locations that work differently.", "Continue recording repair and service details regardless of the invoice setting."], action: "Review customer invoicing" },
  },
  de: {
    managerOverview: { title: "Ihre Werkstattübersicht", purpose: "Hier sehen Sie Werkstattzugriff, betriebliche Hinweise und Bereiche, die noch Aufmerksamkeit benötigen.", why: "Vollständige Werkstattdaten und realistische Einstellungen verbessern die Auffindbarkeit und vermeiden Buchungsprobleme.", steps: ["Öffentliches Werkstattprofil vervollständigen.", "Anfragbare Leistungen veröffentlichen.", "Kapazität, Ressourcen und wichtigen Bestand konfigurieren."], action: "Werkstatteinstellungen öffnen" },
    organisationOverview: { title: "Ihre Organisationsübersicht", purpose: "Vergleichen Sie Standorte, Auslastung, Qualitätssignale und Ausnahmen an einer Stelle.", why: "Einheitliche Einstellungen machen Lücken bei Leistungen, Kapazität und Bestand sichtbar.", steps: ["Manager und Abdeckung jedes Standorts prüfen.", "Leistungen und Kapazität standortübergreifend vergleichen.", "Bestands- und Qualitätshinweise regelmäßig prüfen."], action: "Standorte verwalten" },
    requests: { title: "Anfragen und Werkstattkalender", purpose: "Bearbeiten Sie Kundenanfragen, Termine und bestätigte Arbeiten für den ausgewählten Standort.", why: "Ein standortbezogener Kalender verhindert Änderungen am falschen Werkstattplan.", steps: ["Werkstattstandort auswählen.", "Neue Anfragen vor der Bestätigung prüfen.", "Bestätigte Arbeiten Personal und Arbeitsplätzen zuweisen."], action: "Werkstattkalender öffnen" },
    capacity: { title: "Kapazität und Ressourcen", purpose: "Verwalten Sie Personal, physische Arbeitsplätze, Tageskapazität und Verfügbarkeit je Standort.", why: "Klare Zuordnungen von Personal zu Arbeitsplätzen machen nutzbare Kapazität sichtbar und vermeiden Konflikte.", steps: ["Personal und Fachgebiete hinzufügen.", "Buchten, Rampen, Hebebühnen und weitere Arbeitsplätze hinzufügen.", "Personal per Ziehen zuordnen und Abwesenheiten oder Wartung erfassen."], action: "Kapazität verwalten" },
    repairs: { title: "Reparaturablauf", purpose: "Führen Sie Arbeiten von Diagnose und Angebot bis Reparatur und Abholung mit klarer Dokumentation.", why: "Einheitliche Statusangaben klären Verantwortung und halten Kundenbenachrichtigungen korrekt.", steps: ["Arbeitsauftrag vor Beginn öffnen.", "Diagnose und erforderliche Freigaben dokumentieren.", "Servicenachweis vor der Abholung abschließen."], action: "Aktive Reparaturen prüfen" },
    quality: { title: "Qualität, Garantie und Erinnerungen", purpose: "Verfolgen Sie Garantiefälle, Wiederholungsreparaturen und Wartungserinnerungen.", why: "Konsequente Erfassung hilft, wiederkehrende Ursachen zu erkennen und Vertrauen zu erhalten.", steps: ["Offene Garantie- und Rückkehrfälle prüfen.", "Ergebnis und Korrekturmaßnahme dokumentieren.", "Fällige Wartungserinnerungen bearbeiten."], action: "Qualität prüfen" },
    profile: { title: "Werkstattprofil und Buchungsregeln", purpose: "Verwalten Sie öffentliche Angaben und Regeln für angebotene Termine.", why: "Logo, Standort, Kontaktdaten und realistische Regeln verbessern Vertrauen und Sichtbarkeit.", steps: ["Logo, Beschreibung und Kontakt ergänzen.", "Kartenstandort und Öffnungszeiten bestätigen.", "Vorlauf, Horizont und Tageskapazität festlegen."], action: "Profil vervollständigen" },
    services: { title: "Leistungskatalog", purpose: "Veröffentlichen Sie Leistungen mit Dauer, Preisorientierung und Buchungsart.", why: "Pitster empfiehlt Werkstätten anhand aktiver Leistungen, die zur Kundenauswahl passen.", steps: ["Zuerst die wichtigsten Leistungen veröffentlichen.", "Realistische Dauer und Einstiegspreise ergänzen.", "Katalog bei neuen Fähigkeiten oder Geräten aktualisieren."], action: "Leistungen verwalten" },
    inventory: { title: "Teile- und Verbrauchsbestand", purpose: "Verfolgen Sie häufig genutzten Bestand, Bewegungen und Mindestmengen.", why: "Sinnvolle Mindestmengen zeigen Engpässe früh und reduzieren Reparaturverzögerungen.", steps: ["Mit Ölen, Filtern, Bremsen und Verbrauchsmaterial beginnen.", "Mindestmengen für wichtige Artikel festlegen.", "Eingänge, Verbrauch und Inventuren erfassen."], action: "Bestand öffnen" },
    locations: { title: "Werkstattstandorte", purpose: "Fügen Sie Standorte hinzu, beanspruchen und konfigurieren Sie sie.", why: "Jeder Standort benötigt korrekte Angaben, einen Manager und aktive Abdeckung.", steps: ["Adresse und öffentliches Profil prüfen.", "Verantwortlichen Manager zuweisen.", "Leistungen, Kapazität und Abdeckung abschließen."], action: "Standorte prüfen" },
    managers: { title: "Werkstattmanager", purpose: "Laden Sie Manager ein und steuern Sie deren Standortverantwortung.", why: "Klare Zuweisungen schützen Daten und leiten Aufgaben an die richtige Person.", steps: ["Manager mit Arbeits-E-Mail einladen.", "Richtigen Standort zuweisen.", "Zugriff bei Änderungen zeitnah entfernen."], action: "Zugriff verwalten" },
    billing: { title: "Abonnement und Abrechnung", purpose: "Prüfen Sie Abdeckung, Abonnementstatus, Rechnungen und kommende Kosten.", why: "Die Abdeckung bestimmt den fortlaufenden Zugriff aktiver Standorte.", steps: ["Unternehmens- und Rechnungsdaten bestätigen.", "Abdeckung jedes Standorts prüfen.", "Zahlungswarnungen rechtzeitig beheben."], action: "Abrechnung prüfen" },
    customerInvoicing: { title: "Kundenrechnungen", purpose: "Legen Sie fest, ob Pitster Rechnungsdaten für Kunden erfasst oder die Werkstatt ausschließlich lokale Software nutzt.", why: "Eine klare Einstellung verhindert doppelte Eingaben, ohne Angebote, Reparaturdaten oder Servicehistorie zu entfernen.", steps: ["Organisationsstandard wählen.", "Nur abweichende Standorte überschreiben.", "Reparatur- und Servicedaten unabhängig davon weiter erfassen."], action: "Kundenrechnungen prüfen" },
  },
  ro: {
    managerOverview: { title: "Prezentarea atelierului", purpose: "Vezi accesul, alertele operaționale și zonele care necesită atenție.", why: "Informațiile complete și setările realiste cresc vizibilitatea și previn problemele de programare.", steps: ["Completează profilul public al atelierului.", "Publică serviciile care pot fi solicitate.", "Configurează capacitatea, resursele și stocul esențial."], action: "Deschide setările atelierului" },
    organisationOverview: { title: "Prezentarea organizației", purpose: "Compară locațiile, volumul de lucru, semnalele de calitate și excepțiile.", why: "Configurarea consecventă face mai ușor de observat lipsurile de servicii, capacitate și stoc.", steps: ["Verifică managerul și acoperirea fiecărei locații.", "Compară serviciile și capacitatea locațiilor.", "Revizuiește alertele de stoc și calitate."], action: "Gestionează locațiile" },
    requests: { title: "Cereri și calendarul atelierului", purpose: "Gestionează cererile, programările și lucrările confirmate pentru locația selectată.", why: "Un calendar specific locației previne modificarea programului atelierului greșit.", steps: ["Selectează locația atelierului.", "Verifică cererile înainte de confirmare.", "Alocă lucrările confirmate personalului și posturilor disponibile."], action: "Deschide calendarul" },
    capacity: { title: "Capacitate și resurse", purpose: "Gestionează personalul, posturile fizice, capacitatea zilnică și disponibilitatea fiecărei locații.", why: "Alocările clare între personal și posturi fac vizibilă capacitatea utilizabilă și reduc conflictele.", steps: ["Adaugă personalul și specializările.", "Adaugă boxe, rampe, elevatoare și alte posturi.", "Trage personalul pe posturi și înregistrează absențele sau mentenanța."], action: "Gestionează capacitatea" },
    repairs: { title: "Ciclul reparației", purpose: "Urmărește lucrările de la diagnoză și ofertă până la reparație și predare.", why: "Actualizările consecvente clarifică responsabilitatea și păstrează corecte notificările clientului.", steps: ["Deschide ordinul înainte de începerea lucrării.", "Înregistrează diagnoza și aprobările necesare.", "Finalizează istoricul înainte de predare."], action: "Verifică reparațiile active" },
    quality: { title: "Calitate, garanții și notificări", purpose: "Urmărește garanțiile, revenirile și notificările de întreținere.", why: "Înregistrarea consecventă ajută la identificarea cauzelor recurente și protejează încrederea.", steps: ["Verifică garanțiile și revenirile deschise.", "Înregistrează rezultatul și acțiunea corectivă.", "Urmărește notificările de întreținere scadente."], action: "Verifică elementele de calitate" },
    profile: { title: "Profilul și regulile atelierului", purpose: "Gestionează informațiile publice și regulile folosite pentru datele programărilor.", why: "Sigla, locația, contactul și regulile realiste îmbunătățesc încrederea și vizibilitatea.", steps: ["Adaugă sigla, descrierea și contactul public.", "Confirmă locația și programul.", "Setează timpul minim, orizontul și capacitatea zilnică."], action: "Completează profilul" },
    services: { title: "Catalogul de servicii", purpose: "Publică serviciile fiecărui atelier, cu durată, preț orientativ și mod de rezervare.", why: "Pitster recomandă atelierele prin potrivirea serviciului ales cu intrările active din catalog.", steps: ["Publică mai întâi serviciile principale.", "Adaugă durate și prețuri inițiale realiste.", "Actualizează catalogul când se schimbă echiparea sau competențele."], action: "Gestionează serviciile" },
    inventory: { title: "Inventarul de piese și consumabile", purpose: "Urmărește stocul folosit frecvent, mișcările și nivelurile de reaprovizionare.", why: "Nivelurile minime utile arată lipsurile devreme și reduc întârzierile reparațiilor.", steps: ["Începe cu uleiuri, filtre, frâne și consumabile.", "Setează cantitatea minimă pentru articole importante.", "Înregistrează recepțiile, consumul și inventarele."], action: "Deschide inventarul" },
    locations: { title: "Locațiile atelierelor", purpose: "Adaugă, revendică și configurează locațiile organizației.", why: "Fiecare locație are nevoie de informații corecte, manager și acoperire activă.", steps: ["Confirmă adresa și profilul public.", "Alocă managerul responsabil.", "Finalizează serviciile, capacitatea și acoperirea."], action: "Verifică locațiile" },
    managers: { title: "Managerii atelierelor", purpose: "Invită manageri și controlează locația de care răspunde fiecare.", why: "Alocările clare protejează datele și trimit sarcinile către persoana potrivită.", steps: ["Invită managerul cu adresa de serviciu.", "Alocă locația corectă.", "Elimină accesul când responsabilitățile se schimbă."], action: "Gestionează accesul" },
    billing: { title: "Abonament și facturare", purpose: "Verifică acoperirea, abonamentul, facturile și costurile viitoare.", why: "Acoperirea determină accesul continuu al locațiilor la instrumentele operaționale.", steps: ["Confirmă datele companiei și facturării.", "Verifică acoperirea fiecărei locații.", "Rezolvă alertele de plată înainte de afectarea accesului."], action: "Verifică facturarea" },
    customerInvoicing: { title: "Facturarea clienților", purpose: "Alege dacă Pitster înregistrează detaliile facturilor pentru clienți sau atelierul folosește exclusiv software-ul local.", why: "O setare clară evită introducerea dublă fără a elimina ofertele, reparațiile sau istoricul de service.", steps: ["Alege valoarea implicită a organizației.", "Suprascrie doar locațiile care lucrează diferit.", "Continuă să înregistrezi reparațiile și istoricul indiferent de setare."], action: "Verifică facturarea clienților" },
  },
  hu: {
    managerOverview: { title: "A műhely áttekintése", purpose: "Itt láthatók a hozzáférések, működési figyelmeztetések és a még elvégzendő beállítások.", why: "A teljes műhelyadatok és reális beállítások javítják a láthatóságot és megelőzik a foglalási gondokat.", steps: ["Egészítse ki a nyilvános műhelyprofilt.", "Tegye közzé a kérhető szolgáltatásokat.", "Állítsa be a kapacitást, erőforrásokat és alapvető készletet."], action: "Műhelybeállítások megnyitása" },
    organisationOverview: { title: "A szervezet áttekintése", purpose: "Hasonlítsa össze a helyszíneket, terhelést, minőségi jeleket és kivételeket.", why: "Az egységes beállítás láthatóvá teszi a szolgáltatási, kapacitási és készlethiányokat.", steps: ["Ellenőrizze minden helyszín vezetőjét és fedezetét.", "Hasonlítsa össze a szolgáltatásokat és kapacitást.", "Rendszeresen nézze át a készlet- és minőségi jelzéseket."], action: "Helyszínek kezelése" },
    requests: { title: "Kérelmek és műhelynaptár", purpose: "Kezelje a kiválasztott helyszín ügyfélkérelmeit, időpontjait és megerősített munkáit.", why: "A helyszínhez kötött naptár megakadályozza a rossz műhely ütemezésének módosítását.", steps: ["Válassza ki a műhely helyszínét.", "Megerősítés előtt ellenőrizze az új kérelmeket.", "Rendelje a munkát elérhető dolgozóhoz és munkaállomáshoz."], action: "Műhelynaptár megnyitása" },
    capacity: { title: "Kapacitás és erőforrások", purpose: "Kezelje helyszínenként a személyzetet, fizikai munkaállomásokat, napi kapacitást és elérhetőséget.", why: "Az egyértelmű személyzet–munkaállomás hozzárendelés láthatóvá teszi a használható kapacitást és csökkenti az ütközéseket.", steps: ["Adja hozzá a személyzetet és szakterületeit.", "Adjon hozzá beállókat, rámpákat, emelőket és más munkaállomásokat.", "Húzza a dolgozókat munkaállomásra, és rögzítse a távollétet vagy karbantartást."], action: "Kapacitás kezelése" },
    repairs: { title: "Javítási folyamat", purpose: "Kövesse a munkát a diagnózistól és ajánlattól a javításon át az átadásig.", why: "A következetes állapotfrissítés tisztázza a felelősséget és pontos értesítéseket biztosít.", steps: ["Munka előtt nyissa meg a munkalapot.", "Rögzítse a diagnózist és a szükséges jóváhagyást.", "Átadás előtt zárja le a szervizelőzményt."], action: "Aktív javítások áttekintése" },
    quality: { title: "Minőség, garancia és emlékeztetők", purpose: "Kövesse a garanciális eseteket, visszatérő javításokat és karbantartási emlékeztetőket.", why: "A következetes rögzítés segít felismerni az ismétlődő okokat és megőrizni a bizalmat.", steps: ["Tekintse át a nyitott garanciális és visszatérési eseteket.", "Rögzítse az eredményt és a javító intézkedést.", "Kövesse a lejárt karbantartási emlékeztetőket."], action: "Minőségi tételek áttekintése" },
    profile: { title: "Műhelyprofil és foglalási szabályok", purpose: "Kezelje a nyilvános adatokat és az ajánlható időpontok szabályait.", why: "A logó, pontos hely, elérhetőség és reális szabályok növelik a bizalmat és láthatóságot.", steps: ["Adjon hozzá logót, leírást és elérhetőséget.", "Ellenőrizze a térképes helyet és nyitvatartást.", "Állítsa be az átfutást, horizontot és napi kapacitást."], action: "Profil kiegészítése" },
    services: { title: "Szolgáltatáskatalógus", purpose: "Tegye közzé a szolgáltatásokat időtartammal, irányárral és foglalási móddal.", why: "A Pitster az aktív katalógus és az ügyfél választása alapján ajánl műhelyt.", steps: ["Először a fő szolgáltatásokat tegye közzé.", "Adjon meg reális időtartamot és induló árat.", "Frissítse a katalógust új eszköz vagy tudás esetén."], action: "Szolgáltatások kezelése" },
    inventory: { title: "Alkatrész- és fogyóanyag-készlet", purpose: "Kövesse a gyakori készletet, mozgásokat és újrarendelési szinteket.", why: "A jó minimumszintek korán jelzik a hiányt és csökkentik a javítási késést.", steps: ["Kezdje olajokkal, szűrőkkel, fékekkel és fogyóanyagokkal.", "Állítson minimumot a fontos tételekhez.", "Rögzítse a bevételezést, felhasználást és leltárt."], action: "Készlet megnyitása" },
    locations: { title: "Műhelyhelyszínek", purpose: "Adja hozzá, igényelje és állítsa be a szervezet helyszíneit.", why: "Minden helyszínhez pontos adat, felelős vezető és aktív fedezet szükséges.", steps: ["Ellenőrizze a címet és nyilvános profilt.", "Rendelje hozzá a felelős vezetőt.", "Fejezze be a szolgáltatás-, kapacitás- és fedezetbeállítást."], action: "Helyszínek áttekintése" },
    managers: { title: "Műhelyvezetők", purpose: "Hívjon meg vezetőket és szabályozza a helyszíni felelősségüket.", why: "Az egyértelmű hozzárendelés védi az adatokat és a megfelelő emberhez irányítja a feladatokat.", steps: ["Munkahelyi e-maillel hívja meg a vezetőt.", "Rendelje hozzá a megfelelő helyszínt.", "Változáskor időben szüntesse meg a hozzáférést."], action: "Hozzáférés kezelése" },
    billing: { title: "Előfizetés és számlázás", purpose: "Tekintse át a fedezetet, előfizetést, számlákat és várható díjakat.", why: "A fedezet határozza meg az aktív helyszínek folyamatos hozzáférését.", steps: ["Ellenőrizze a cég- és számlázási adatokat.", "Tekintse át minden helyszín fedezetét.", "Oldja meg a fizetési jelzéseket a hozzáférés érintése előtt."], action: "Számlázás áttekintése" },
    customerInvoicing: { title: "Ügyfélszámlázási beállítás", purpose: "Döntse el, hogy a Pitster rögzítse-e az ügyfélszámla adatait, vagy a műhely csak helyi szoftvert használjon.", why: "Az egyértelmű beállítás elkerüli a kettős adatrögzítést az ajánlatok, javítási adatok és szervizelőzmények megtartásával.", steps: ["Válassza ki a szervezeti alapértéket.", "Csak az eltérően működő helyszíneket írja felül.", "A javítási és szervizadatokat ettől függetlenül továbbra is rögzítse."], action: "Ügyfélszámlázás áttekintése" },
  },
};

const routes: Record<GuidanceRole, Array<{ path: string; key: string; copyId: CopyId; href: string }>> = {
  workshop_manager: [
    { path: "/workshop-manager/capacity", key: "manager_capacity", copyId: "capacity", href: "/workshop-manager/capacity" },
    { path: "/workshop-manager/requests", key: "manager_requests", copyId: "requests", href: "/workshop-manager/requests" },
    { path: "/workshop-manager/repairs", key: "manager_repairs", copyId: "repairs", href: "/workshop-manager/repairs" },
    { path: "/workshop-manager/quality", key: "manager_quality", copyId: "quality", href: "/workshop-manager/quality" },
    { path: "/workshop-manager/workshops", key: "manager_workshop_profile", copyId: "profile", href: "/workshop-manager/workshops" },
    { path: "/workshop-manager/services", key: "manager_services", copyId: "services", href: "/workshop-manager/services" },
    { path: "/workshop-manager/inventory", key: "manager_inventory", copyId: "inventory", href: "/workshop-manager/inventory" },
    { path: "/workshop-manager/organisation", key: "manager_organisation", copyId: "locations", href: "/workshop-manager/organisation" },
    { path: "/workshop-manager/invoicing", key: "manager_invoicing", copyId: "customerInvoicing", href: "/workshop-manager/invoicing" },
    { path: "/workshop-manager", key: "manager_overview", copyId: "managerOverview", href: "/workshop-manager/workshops" },
  ],
  service_organisation: [
    { path: "/service-organisation/capacity", key: "organisation_capacity", copyId: "capacity", href: "/service-organisation/capacity" },
    { path: "/service-organisation/requests", key: "organisation_requests", copyId: "requests", href: "/service-organisation/requests" },
    { path: "/service-organisation/repairs", key: "organisation_repairs", copyId: "repairs", href: "/service-organisation/repairs" },
    { path: "/service-organisation/quality", key: "organisation_quality", copyId: "quality", href: "/service-organisation/quality" },
    { path: "/service-organisation/locations", key: "organisation_locations", copyId: "locations", href: "/service-organisation/locations" },
    { path: "/service-organisation/services", key: "organisation_services", copyId: "services", href: "/service-organisation/services" },
    { path: "/service-organisation/managers", key: "organisation_managers", copyId: "managers", href: "/service-organisation/managers" },
    { path: "/service-organisation/inventory", key: "organisation_inventory", copyId: "inventory", href: "/service-organisation/inventory" },
    { path: "/service-organisation/billing", key: "organisation_billing", copyId: "billing", href: "/service-organisation/billing" },
    { path: "/service-organisation/settings", key: "organisation_settings", copyId: "customerInvoicing", href: "/service-organisation/settings" },
    { path: "/service-organisation", key: "organisation_overview", copyId: "organisationOverview", href: "/service-organisation/locations" },
  ],
};

export function guidanceFor(role: GuidanceRole, pathname: string, language: Language): GuidanceDefinition | null {
  const route = routes[role].find((item) => pathname === item.path || pathname.startsWith(`${item.path}/`));
  if (!route) return null;
  return { ...copy[language][route.copyId], key: route.key, version: 1, href: route.href };
}
