"use client";

import Link from "next/link";
import { locales, translate, type TranslationKey } from "@/app/i18n";
import { useLanguage } from "@/app/i18n/useLanguage";
import type { GarageVehicle } from "@/lib/dal/garage";
import type { VehicleServiceRecord } from "@/lib/dal/vehicle-service-history";
import { CustomerPageGuide } from "@/app/guidance/CustomerGuidance";

export default function VehicleServiceHistoryClient({ vehicle, records }: { vehicle: GarageVehicle; records: VehicleServiceRecord[] }) {
  const [language, , ready] = useLanguage(); const t = (key: TranslationKey) => translate(language, key);
  if (!ready) return <main className="registration-shell" aria-busy="true" />;
  const money = (cents: number, currency: string) => new Intl.NumberFormat(locales[language], { style: "currency", currency }).format(cents / 100);
  const upcoming = records.flatMap((record) => record.recommendations.filter((item) => !item.completedAt).map((item) => ({ ...item, recordId: record.id })));
  return <main className="settings-shell service-history-shell"><header className="settings-topbar"><Link href="/garage">← {t("workspace.back")}</Link><strong>pitster</strong><a href={`/api/vehicles/${vehicle.id}/service-history`}>{t("serviceHistory.downloadPdf")}</a></header><section className="settings-content service-history-content">
    <header className="service-history-hero"><div><p>{t("serviceHistory.eyebrow")}</p><h1>{vehicle.make} {vehicle.model}</h1><span>{vehicle.registrationNumber}{vehicle.productionYear ? ` · ${vehicle.productionYear}` : ""}</span></div><dl><div><dt>VIN</dt><dd>{vehicle.vin ?? t("serviceHistory.notRecorded")}</dd></div><div><dt>{t("serviceHistory.mileage")}</dt><dd>{vehicle.currentMileageKm === null ? t("serviceHistory.notRecorded") : `${vehicle.currentMileageKm.toLocaleString(locales[language])} km`}</dd></div></dl></header>
    <CustomerPageGuide title={t("phase6.history.title")} description={t("phase6.history.description")} steps={[t("phase6.history.step1"), t("phase6.history.step2"), t("phase6.history.step3")]} />
    {upcoming.length > 0 && <section className="service-history-upcoming"><header><p>{t("serviceHistory.upcoming")}</p><h2>{upcoming.length} {t("serviceHistory.recommendations")}</h2></header><div>{upcoming.map((item, index) => <article key={`${item.recordId}-${index}`}><strong>{item.description}</strong><span>{[item.dueOn ? new Intl.DateTimeFormat(locales[language], { dateStyle: "medium" }).format(new Date(item.dueOn)) : null, item.dueMileageKm ? `${item.dueMileageKm.toLocaleString(locales[language])} km` : null].filter(Boolean).join(" · ") || t("serviceHistory.noDueDate")}</span></article>)}</div></section>}
    <section className="service-history-timeline"><header><p>{t("serviceHistory.timeline")}</p><h2>{records.length} {t("serviceHistory.completedVisits")}</h2></header>{records.map((record) => <article key={record.id}><aside><time>{record.completedAt ? new Intl.DateTimeFormat(locales[language], { dateStyle: "long" }).format(new Date(record.completedAt)) : "—"}</time><span>{record.mileageKm === null ? "—" : `${record.mileageKm.toLocaleString(locales[language])} km`}</span></aside><div><header><div><p>{record.workshopName}</p><h3>{record.serviceName}</h3></div>{record.invoiceTotalCents !== null && record.invoiceCurrency && <strong>{money(record.invoiceTotalCents, record.invoiceCurrency)}</strong>}</header>{record.workSummary && <section><h4>{t("serviceHistory.workSummary")}</h4><p>{record.workSummary}</p></section>}{record.inspectionSummary && <section><h4>{t("serviceHistory.inspection")}</h4><p>{record.inspectionSummary}</p></section>}{record.parts.length > 0 && <section><h4>{t("serviceHistory.parts")}</h4><ul>{record.parts.map((part, index) => <li key={index}><span><b>{part.description}</b>{part.partNumber && <small>{part.partNumber}</small>}</span><span>{part.quantity}×{part.warrantyExpiresOn && <small>{t("serviceHistory.warrantyUntil")} {new Intl.DateTimeFormat(locales[language], { dateStyle: "medium" }).format(new Date(part.warrantyExpiresOn))}</small>}</span></li>)}</ul></section>}{record.invoiceNumber && <footer><b>{t("serviceHistory.invoice")} {record.invoiceNumber}</b>{record.invoiceIssuedOn && <span>{new Intl.DateTimeFormat(locales[language], { dateStyle: "medium" }).format(new Date(record.invoiceIssuedOn))}</span>}</footer>}</div></article>)}{!records.length && <div className="catalogue-empty"><h2>{t("serviceHistory.emptyTitle")}</h2><p>{t("phase6.history.emptyDescription")}</p><Link className="organization-action" href="/workshops">{t("phase6.history.bookService")}</Link></div>}</section>
  </section></main>;
}
