import type { Language } from "@/app/i18n";

export type LegalDocumentType = "terms" | "privacy" | "cookies";
type LegalSection = { id: string; title: string; paragraphs: string[]; items?: string[] };
type LegalDocument = {
  kicker: string; title: string; introduction: string; effectiveDate: string; contentsLabel: string;
  sections: LegalSection[]; sourcesTitle: string; sources: Array<{ label: string; href: string }>;
  closureTitle: string; closureDescription: string; closureAction: string;
  footerTerms: string; footerPrivacy: string; footerCookies: string;
};

const sources = {
  gdpr: { label: "EU General Data Protection Regulation", href: "https://eur-lex.europa.eu/eli/reg/2016/679/oj" },
  authority: { label: "Romanian data-protection authority (ANSPDCP)", href: "https://www.dataprotection.ro/" },
  euCookies: { label: "European Commission cookie information", href: "https://commission.europa.eu/cookies-policy_en" },
  googlePrivacy: { label: "Google Privacy Policy", href: "https://policies.google.com/privacy" },
  googleMaps: { label: "Google Maps Platform Terms", href: "https://cloud.google.com/maps-platform/terms" },
};

const common = {
  effectiveDate: "Effective 14 August 2026",
  contentsLabel: "On this page",
  closureTitle: "Request account closure",
  closureDescription: "Send a written account-closure request through the secure form. An administrator verifies the request, blocks or deactivates the account first, and records a 30- or 60-day deletion follow-up. Data that must be retained for legal, billing, fraud-prevention, or dispute purposes is handled separately.",
  closureAction: "Start an account-closure request",
  footerTerms: "Terms", footerPrivacy: "Privacy", footerCookies: "Cookies",
};

const en: Record<LegalDocumentType, LegalDocument> = {
  terms: {
    ...common, kicker: "Legal information", title: "Terms and conditions",
    introduction: "These terms describe the rules for customers, Service Organisations, Workshop Managers, and visitors using Pitster.",
    sections: [
      { id: "platform", title: "The platform and its roles", paragraphs: ["Pitster is a digital vehicle-service platform that helps customers discover workshops, request appointments, exchange service information, and follow repair progress. Service Organisations manage one or more locations and their subscriptions. Workshop Managers operate only locations assigned to them.", "Pitster provides the platform and administrative infrastructure. Unless expressly stated, Pitster is not the workshop performing diagnosis or repair and is not a party to the workshop’s service contract with the customer."] },
      { id: "accounts", title: "Accounts and authorised access", paragraphs: ["You must provide accurate information, protect your credentials, and use only the account role and workshop locations authorised for you. Workshop Manager access is invitation-only. Service Organisations are responsible for invitations, assigned locations, and the actions of their authorised users.", "Tell Pitster promptly if credentials, permissions, or account information may have been compromised. Pitster may require identity or authority verification before processing sensitive account changes."] },
      { id: "appointments", title: "Appointments, estimates, and payments", paragraphs: ["An appointment request is not confirmed until the workshop accepts it or the customer accepts a proposed alternative. Workshop descriptions, availability, diagnosis fees, estimates, repair decisions, warranties, and invoices are supplied or managed by the relevant service provider.", "Service Organisation platform subscriptions are processed through Stripe under the billing rules shown in the organisation workspace. Charges for vehicle work are agreed between customer and workshop unless Pitster explicitly offers a separate payment service."] },
      { id: "content", title: "Vehicle and workshop information", paragraphs: ["Customers and authorised service professionals must enter information they reasonably believe to be accurate. Service professionals may add inspection findings, service-history entries, fitted parts, warranties, and repair updates only where they have an authorised service relationship with the customer or vehicle.", "Do not upload unlawful content, malicious code, passwords, unnecessary sensitive data, or information that infringes another person’s rights. Workshop listings must accurately describe the business, location, services, and authority to operate."] },
      { id: "external", title: "External services", paragraphs: ["Pitster uses third-party infrastructure and services, including Supabase, Vercel, Stripe, MXroute, SMS delivery providers, Meta WhatsApp Business Platform, and Google Maps. Availability may depend on those services. Use of Google Maps and WhatsApp features is also subject to the applicable provider terms and privacy notices."] },
      { id: "suspension", title: "Suspension, closure, and liability", paragraphs: ["Pitster may restrict, suspend, or block an account to protect users, investigate misuse, meet legal obligations, or respond to a verified closure request. Account closure and personal-data erasure are handled under the Privacy Policy; some records may remain where retention is legally required.", "To the extent permitted by law, Pitster does not guarantee uninterrupted access, workshop performance, or the accuracy of information supplied by independent users. Nothing in these terms limits mandatory consumer rights or liability that cannot lawfully be excluded."] },
      { id: "changes", title: "Changes and contact", paragraphs: ["Pitster may update these terms when platform functions, providers, or legal requirements change. Material updates will be presented through the platform or another appropriate channel. Questions and formal requests can be submitted through the Contact page."] },
    ], sourcesTitle: "Relevant external terms", sources: [sources.googleMaps, sources.googlePrivacy],
  },
  privacy: {
    ...common, kicker: "Personal data", title: "Privacy policy",
    introduction: "This policy explains what Pitster processes, why it is needed, who can access it, and how to exercise your rights.",
    sections: [
      { id: "controller", title: "Controller and contact", paragraphs: ["The Pitster platform operator determines how platform account and marketplace data is processed. Privacy and data-rights requests can be submitted through the Contact page or to support@pitster.app. The contracting entity shown in a provider agreement or invoice remains responsible for its own processing activities."] },
      { id: "data", title: "Data we process", paragraphs: ["Depending on your role and use of the platform, data may include identity and contact details, authentication identifiers, vehicles and optional VIN or mileage, garage records, appointment requests, repair lifecycle information, estimates, invoices, service history, warranties, workshop and organisation details, staff assignments, billing records, support tickets, and technical security logs."], items: ["Customer information entered directly by the customer.", "Service information entered by a workshop professional who has an authorised relationship with the customer or vehicle.", "Organisation, workshop, billing, and access information supplied by service providers.", "Technical information generated for authentication, security, communications, and platform reliability."] },
      { id: "purposes", title: "Purposes and legal bases", paragraphs: ["Pitster processes data to create and secure accounts, provide appointment and repair functions, maintain portable service history, send requested service communications, administer subscriptions, prevent misuse, resolve support tickets, and comply with legal duties.", "The applicable basis may be performance of a contract, steps requested before a contract, compliance with a legal obligation, legitimate interests in operating and protecting the platform, or consent where the law specifically requires it. A privacy acknowledgement is not consent to optional advertising or analytics."] },
      { id: "access", title: "Access, sharing, and service providers", paragraphs: ["Access is role- and location-restricted. Platform administrators and Service Organisation managers do not have routine access to customer garage content. Workshop professionals may access or add service data only through an authorised customer, booking, vehicle, or location relationship. Customers can view their information and manage available sharing permissions.", "Technical processors may include Supabase, Vercel, MXroute, Stripe, SMS providers, Meta WhatsApp Business Platform, and Google Maps. They receive only the information needed for their function and operate under their own terms and applicable data-protection arrangements. WhatsApp is used only after operational-message opt-in and can be disabled per booking or by sending STOP. Google may receive technical device, connection, and request information when a map loads."] },
      { id: "retention", title: "Retention and account closure", paragraphs: ["Operational account and service data is kept while it is needed to provide the platform and maintain legitimate service records. A verified closure request begins with account blocking or deactivation. An administrator then schedules a deletion review after either 30 or 60 days, records the due date, and follows up through the admin ticket queue.", "Erasure is not absolute. Invoices, payment evidence, security logs, dispute records, warranty evidence, or other records may be retained where law or overriding legitimate grounds require it. Backups may expire on separate controlled cycles. Data is deleted or anonymised when the applicable purpose and retention period end."] },
      { id: "rights", title: "Your data-protection rights", paragraphs: ["Subject to the GDPR and applicable law, you may request access, correction, erasure, restriction, portability, or objection, and may withdraw consent where processing depends on consent. Pitster may ask for proportionate identity verification and will explain if a request cannot be fulfilled in full.", "You may complain to the Romanian data-protection authority, ANSPDCP, or another competent supervisory authority. Exercising a right does not affect mandatory records belonging to another party or the rights and freedoms of others."] },
      { id: "security", title: "Security and updates", paragraphs: ["Pitster uses access controls, row-level database policies, role separation, secure authentication, audit records, and protected administrative operations. No online system can be guaranteed risk-free. Report suspected misuse through the problem-report form.", "This policy may be updated as services or legal requirements change. Material changes will be identified by a revised effective date and, where appropriate, an in-platform notice."] },
    ], sourcesTitle: "Privacy references", sources: [sources.gdpr, sources.authority, sources.googlePrivacy],
  },
  cookies: {
    ...common, kicker: "Storage and external services", title: "Cookies and external-services policy",
    introduction: "Pitster currently uses essential authentication and preference storage, together with external services needed for core platform functions.",
    sections: [
      { id: "essential", title: "Essential technologies", paragraphs: ["Pitster uses cookies or equivalent browser storage required for secure authentication, session continuity, language selection, navigation preferences, and acknowledgement of the privacy notice. These technologies are necessary to deliver requested platform functions and protect accounts."] },
      { id: "maps", title: "Google Maps", paragraphs: ["Google Maps supports workshop location display, address search, and geographic discovery. When a map or address-search feature loads, the browser connects to Google services. Google may process IP address, device and browser information, request details, and cookies or similar identifiers under Google’s terms and privacy policy.", "Pitster does not use Google Maps to build an advertising profile. Google’s own processing is controlled by Google and may include transfers or retention described in its policies."] },
      { id: "other-services", title: "Other external services", paragraphs: ["Authentication and database services may use essential session cookies. Stripe handles subscription checkout and billing portals. MXroute, SMS providers, and Meta WhatsApp Business Platform deliver operational messages. Vercel provides web hosting and security infrastructure. These services may create technical logs needed to deliver, secure, and troubleshoot their functions."] },
      { id: "optional", title: "Advertising and analytics", paragraphs: ["Pitster does not currently set optional advertising cookies or operate optional behavioural analytics through this notice. If optional technologies are introduced, they will be clearly separated and, where required, offered through a genuine consent choice. Clicking “I understand” only records that the information was read."] },
      { id: "controls", title: "Your controls", paragraphs: ["Browser controls can remove or block stored data, but blocking essential authentication storage may prevent sign-in or other requested functions. Clearing local storage will reset language, sidebar, and privacy-notice preferences. Google privacy controls are available through Google’s own account and browser settings."] },
      { id: "changes", title: "Changes and questions", paragraphs: ["This policy will be updated if the platform adds new storage categories or external services. Questions can be submitted as a support ticket through the Contact page."] },
    ], sourcesTitle: "External-service information", sources: [sources.euCookies, sources.googlePrivacy, sources.googleMaps],
  },
};

const roCommon = { ...common, effectiveDate: "În vigoare din 14 august 2026", contentsLabel: "Pe această pagină", closureTitle: "Solicită închiderea contului", closureDescription: "Trimite o solicitare scrisă prin formularul securizat. Un administrator verifică solicitarea, blochează sau dezactivează mai întâi contul și programează verificarea ștergerii după 30 sau 60 de zile. Datele care trebuie păstrate din motive legale, de facturare, prevenire a fraudei sau litigii sunt tratate separat.", closureAction: "Începe solicitarea de închidere", footerTerms: "Termeni", footerPrivacy: "Confidențialitate", footerCookies: "Cookie-uri" };
const ro: Record<LegalDocumentType, LegalDocument> = {
  terms: { ...roCommon, kicker: "Informații juridice", title: "Termeni și condiții", introduction: "Acești termeni descriu regulile pentru clienți, Organizații de service, Manageri de atelier și vizitatorii Pitster.", sections: [
    { id: "platform", title: "Platforma și rolurile", paragraphs: ["Pitster este o platformă digitală pentru servicii auto, care ajută clienții să găsească ateliere, să solicite programări și să urmărească reparațiile. Organizațiile de service gestionează locații și abonamente, iar Managerii de atelier operează numai locațiile alocate.", "Pitster furnizează infrastructura platformei. Dacă nu se precizează altfel, Pitster nu este atelierul care efectuează diagnosticul sau reparația și nu este parte în contractul de service dintre client și atelier."] },
    { id: "accounts", title: "Conturi și acces autorizat", paragraphs: ["Trebuie să furnizezi informații corecte, să protejezi datele de autentificare și să folosești numai rolul și locațiile autorizate. Accesul Managerului de atelier se face exclusiv prin invitație.", "Anunță Pitster dacă datele de acces sau permisiunile pot fi compromise. Pentru modificări sensibile poate fi necesară verificarea identității sau a autorității."] },
    { id: "appointments", title: "Programări, estimări și plăți", paragraphs: ["O solicitare nu este confirmată până când atelierul nu o acceptă sau clientul nu acceptă alternativa propusă. Disponibilitatea, diagnosticul, estimările, garanțiile și facturile sunt gestionate de furnizorul relevant.", "Abonamentele Organizațiilor de service sunt procesate prin Stripe. Costurile lucrărilor auto sunt convenite între client și atelier, dacă Pitster nu oferă explicit un serviciu separat de plată."] },
    { id: "content", title: "Informații despre vehicul și atelier", paragraphs: ["Clienții și profesioniștii autorizați trebuie să introducă informații pe care le consideră corecte. Profesioniștii pot adăuga inspecții, istoric, piese, garanții și actualizări numai în cadrul unei relații de service autorizate.", "Nu încărca date ilegale, cod malițios, parole, date sensibile inutile sau informații care încalcă drepturile altora."] },
    { id: "external", title: "Servicii externe", paragraphs: ["Pitster folosește servicii precum Supabase, Vercel, Stripe, MXroute, furnizori SMS, Meta WhatsApp Business Platform și Google Maps. Disponibilitatea poate depinde de acestea, iar funcțiile WhatsApp și Google Maps sunt supuse termenilor furnizorilor aplicabili."] },
    { id: "suspension", title: "Suspendare, închidere și răspundere", paragraphs: ["Pitster poate restricționa, suspenda sau bloca un cont pentru protecție, investigarea abuzurilor, obligații legale sau o solicitare verificată de închidere. Ștergerea datelor este descrisă în Politica de confidențialitate.", "În limitele legii, Pitster nu garantează acces neîntrerupt, prestația atelierului sau exactitatea informațiilor furnizate de utilizatori independenți. Drepturile obligatorii ale consumatorilor rămân neafectate."] },
    { id: "changes", title: "Modificări și contact", paragraphs: ["Termenii pot fi actualizați când se schimbă funcțiile sau cerințele legale. Modificările importante vor fi comunicate în platformă. Întrebările și solicitările formale se trimit prin pagina Contact."] },
  ], sourcesTitle: "Termeni externi relevanți", sources: [sources.googleMaps, sources.googlePrivacy] },
  privacy: { ...roCommon, kicker: "Date personale", title: "Politica de confidențialitate", introduction: "Această politică explică ce date procesează Pitster, de ce sunt necesare, cine le poate accesa și cum îți exerciți drepturile.", sections: [
    { id: "controller", title: "Operator și contact", paragraphs: ["Operatorul platformei Pitster stabilește modul de prelucrare a datelor de cont și marketplace. Solicitările privind datele pot fi trimise prin pagina Contact sau la support@pitster.app. Entitatea din contractul sau factura unui furnizor răspunde de propriile activități de prelucrare."] },
    { id: "data", title: "Datele prelucrate", paragraphs: ["În funcție de rol, datele pot include identitate și contact, autentificare, vehicule, VIN sau kilometraj opțional, garaj, programări, reparații, estimări, facturi, istoric, garanții, organizații și ateliere, alocări, facturare, tichete și jurnale tehnice."], items: ["Date introduse direct de client.", "Date de service introduse de un profesionist cu o relație autorizată.", "Date despre organizație, atelier, facturare și acces.", "Date tehnice pentru securitate, comunicare și fiabilitate."] },
    { id: "purposes", title: "Scopuri și temeiuri", paragraphs: ["Datele sunt folosite pentru conturi, securitate, programări, reparații, istoric, comunicări, abonamente, prevenirea abuzurilor, suport și obligații legale.", "Temeiul poate fi contractul, demersuri precontractuale, obligația legală, interesul legitim sau consimțământul când este cerut. Confirmarea informării nu este consimțământ pentru publicitate sau analiză opțională."] },
    { id: "access", title: "Acces și destinatari", paragraphs: ["Accesul este limitat după rol și locație. Administratorii platformei și managerii Organizației nu au acces obișnuit la conținutul garajului clientului. Profesioniștii pot accesa datele doar printr-o relație autorizată. Clienții își pot vedea informațiile și gestiona permisiunile disponibile.", "Furnizorii tehnici pot include Supabase, Vercel, MXroute, Stripe, servicii SMS și Google Maps. Google poate primi date tehnice despre dispozitiv, conexiune și cerere când se încarcă harta."] },
    { id: "retention", title: "Păstrare și închiderea contului", paragraphs: ["Datele sunt păstrate cât timp sunt necesare. O solicitare verificată începe prin blocarea sau dezactivarea contului. Administratorul programează apoi verificarea ștergerii după 30 sau 60 de zile și urmărește termenul în tichetul administrativ.", "Ștergerea nu este absolută. Facturile, plățile, jurnalele de securitate, litigiile și garanțiile pot fi păstrate conform legii. Copiile de siguranță au cicluri separate controlate."] },
    { id: "rights", title: "Drepturile tale", paragraphs: ["Conform GDPR, poți solicita acces, rectificare, ștergere, restricționare, portabilitate sau opoziție și poți retrage consimțământul unde este relevant. Pitster poate solicita verificarea proporțională a identității.", "Poți depune plângere la ANSPDCP sau la o altă autoritate competentă. Drepturile altor persoane și înregistrările obligatorii rămân protejate."] },
    { id: "security", title: "Securitate și actualizări", paragraphs: ["Pitster folosește control al accesului, politici la nivel de rând, separarea rolurilor, autentificare sigură și audit. Niciun sistem online nu este lipsit de risc. Raportează suspiciunile prin formular.", "Politica poate fi actualizată. Modificările importante vor avea o nouă dată de intrare în vigoare și, când este cazul, o notificare în platformă."] },
  ], sourcesTitle: "Referințe privind confidențialitatea", sources: [sources.gdpr, sources.authority, sources.googlePrivacy] },
  cookies: { ...roCommon, kicker: "Stocare și servicii externe", title: "Politica privind cookie-urile și serviciile externe", introduction: "Pitster folosește în prezent stocare esențială pentru autentificare și preferințe, precum și servicii externe necesare funcțiilor de bază.", sections: [
    { id: "essential", title: "Tehnologii esențiale", paragraphs: ["Pitster folosește cookie-uri sau stocare echivalentă necesare autentificării, sesiunii, limbii, navigării și confirmării informării. Acestea sunt necesare pentru funcțiile solicitate și protecția conturilor."] },
    { id: "maps", title: "Google Maps", paragraphs: ["Google Maps oferă hărți, căutarea adreselor și descoperirea geografică. La încărcare, browserul se conectează la Google, care poate prelucra adresa IP, informații despre dispozitiv și browser, cereri și identificatori conform propriilor politici.", "Pitster nu folosește Google Maps pentru a crea profiluri publicitare. Prelucrarea proprie Google este controlată de Google."] },
    { id: "other-services", title: "Alte servicii externe", paragraphs: ["Autentificarea poate folosi cookie-uri esențiale. Stripe gestionează abonamentele, MXroute, furnizorii SMS și Meta WhatsApp Business Platform transmit mesaje operaționale, iar Vercel furnizează găzduire și securitate. WhatsApp este folosit numai după acord și poate fi dezactivat pentru fiecare programare sau prin mesajul STOP."] },
    { id: "optional", title: "Publicitate și analiză", paragraphs: ["Pitster nu setează în prezent cookie-uri publicitare opționale și nu operează analiză comportamentală opțională prin această informare. Dacă vor fi introduse, vor avea o alegere reală de consimțământ unde este necesar. „Am înțeles” confirmă doar citirea."] },
    { id: "controls", title: "Opțiunile tale", paragraphs: ["Browserul poate șterge sau bloca stocarea, dar blocarea celei esențiale poate împiedica autentificarea. Ștergerea stocării locale resetează limba, bara laterală și confirmarea informării. Controalele Google sunt disponibile în setările Google și ale browserului."] },
    { id: "changes", title: "Modificări și întrebări", paragraphs: ["Politica va fi actualizată dacă apar noi categorii sau servicii externe. Întrebările se trimit printr-un tichet de suport."] },
  ], sourcesTitle: "Informații despre servicii externe", sources: [sources.euCookies, sources.googlePrivacy, sources.googleMaps] },
};

const deCommon = { ...common, effectiveDate: "Gültig ab 14. August 2026", contentsLabel: "Auf dieser Seite", closureTitle: "Kontoschließung beantragen", closureDescription: "Senden Sie einen schriftlichen Antrag über das sichere Formular. Ein Administrator prüft den Antrag, sperrt oder deaktiviert zuerst das Konto und plant die Löschprüfung nach 30 oder 60 Tagen. Gesetzlich, abrechnungsbedingt oder zur Streit- und Betrugsprävention erforderliche Daten werden getrennt behandelt.", closureAction: "Kontoschließung beantragen", footerTerms: "Bedingungen", footerPrivacy: "Datenschutz", footerCookies: "Cookies" };
const de: Record<LegalDocumentType, LegalDocument> = {
  terms: { ...deCommon, kicker: "Rechtliche Informationen", title: "Allgemeine Geschäftsbedingungen", introduction: "Diese Bedingungen regeln die Nutzung von Pitster durch Kunden, Serviceorganisationen, Werkstattleiter und Besucher.", sections: [
    { id: "platform", title: "Plattform und Rollen", paragraphs: ["Pitster ist eine digitale Fahrzeugservice-Plattform für Werkstattsuche, Terminanfragen, Serviceinformationen und Reparaturstatus. Serviceorganisationen verwalten Standorte und Abonnements; Werkstattleiter arbeiten nur für zugewiesene Standorte.", "Pitster stellt die Plattform bereit, führt aber grundsätzlich keine Diagnose oder Reparatur aus und ist nicht Partei des Servicevertrags zwischen Kunde und Werkstatt."] },
    { id: "accounts", title: "Konten und berechtigter Zugriff", paragraphs: ["Angaben müssen richtig, Zugangsdaten geschützt und nur berechtigte Rollen und Standorte verwendet werden. Werkstattleiterkonten entstehen ausschließlich durch Einladung. Serviceorganisationen verantworten Einladungen und Zuweisungen.", "Mögliche Kompromittierungen sind unverzüglich zu melden. Für sensible Änderungen kann Pitster einen Identitäts- oder Berechtigungsnachweis verlangen."] },
    { id: "appointments", title: "Termine, Kostenvoranschläge und Zahlungen", paragraphs: ["Eine Anfrage ist erst bestätigt, wenn die Werkstatt sie annimmt oder der Kunde einen Alternativtermin akzeptiert. Leistungen, Diagnosegebühren, Kostenvoranschläge, Garantien und Rechnungen verantwortet der jeweilige Anbieter.", "Plattformabonnements werden über Stripe verarbeitet. Fahrzeugarbeiten werden zwischen Kunde und Werkstatt vereinbart, sofern Pitster nicht ausdrücklich einen eigenen Zahlungsdienst anbietet."] },
    { id: "content", title: "Fahrzeug- und Werkstattdaten", paragraphs: ["Kunden und berechtigte Fachkräfte müssen nach bestem Wissen richtige Daten eingeben. Servicedaten dürfen nur bei einer berechtigten Kunden-, Fahrzeug- oder Servicebeziehung ergänzt werden.", "Unzulässige Inhalte, Schadcode, Passwörter, unnötige sensible Daten und rechtsverletzende Informationen sind verboten."] },
    { id: "external", title: "Externe Dienste", paragraphs: ["Pitster nutzt unter anderem Supabase, Vercel, Stripe, MXroute, SMS-Anbieter, die Meta WhatsApp Business Platform und Google Maps. Die Verfügbarkeit kann davon abhängen. WhatsApp- und Google-Maps-Funktionen unterliegen zusätzlich den geltenden Anbieterbedingungen."] },
    { id: "suspension", title: "Sperrung, Schließung und Haftung", paragraphs: ["Pitster darf Konten zum Schutz der Nutzer, zur Missbrauchsprüfung, zur Erfüllung gesetzlicher Pflichten oder nach einem bestätigten Schließungsantrag einschränken oder sperren. Löschung und Aufbewahrung richten sich nach der Datenschutzrichtlinie.", "Soweit gesetzlich zulässig, garantiert Pitster weder ununterbrochenen Zugang noch Werkstattleistungen oder die Richtigkeit fremder Angaben. Zwingende Verbraucherrechte bleiben unberührt."] },
    { id: "changes", title: "Änderungen und Kontakt", paragraphs: ["Bei Funktions- oder Rechtsänderungen können diese Bedingungen aktualisiert werden. Wesentliche Änderungen werden angemessen mitgeteilt. Formelle Anfragen sind über die Kontaktseite einzureichen."] },
  ], sourcesTitle: "Relevante externe Bedingungen", sources: [sources.googleMaps, sources.googlePrivacy] },
  privacy: { ...deCommon, kicker: "Personenbezogene Daten", title: "Datenschutzrichtlinie", introduction: "Diese Richtlinie erklärt, welche Daten Pitster verarbeitet, warum sie benötigt werden, wer darauf zugreifen kann und wie Rechte ausgeübt werden.", sections: [
    { id: "controller", title: "Verantwortlicher und Kontakt", paragraphs: ["Der Betreiber der Pitster-Plattform bestimmt die Verarbeitung von Konto- und Marktplatzdaten. Datenschutzanfragen können über die Kontaktseite oder an support@pitster.app gesendet werden. Die in einem Vertrag oder einer Rechnung genannte Einheit bleibt für eigene Verarbeitungsvorgänge verantwortlich."] },
    { id: "data", title: "Verarbeitete Daten", paragraphs: ["Je nach Rolle können Identitäts-, Kontakt- und Authentifizierungsdaten, Fahrzeuge, optionale FIN und Kilometerstände, Garage, Termine, Reparaturen, Kostenvoranschläge, Rechnungen, Servicehistorie, Garantien, Organisations- und Werkstattdaten, Zuweisungen, Abrechnung, Support-Tickets und Sicherheitsprotokolle verarbeitet werden."], items: ["Vom Kunden eingegebene Daten.", "Servicedaten einer berechtigten Fachkraft.", "Organisations-, Werkstatt-, Abrechnungs- und Zugriffsdaten.", "Technische Daten für Sicherheit, Kommunikation und Zuverlässigkeit."] },
    { id: "purposes", title: "Zwecke und Rechtsgrundlagen", paragraphs: ["Die Verarbeitung dient Konten, Sicherheit, Terminen, Reparaturabläufen, Servicehistorie, Mitteilungen, Abonnements, Missbrauchsschutz, Support und gesetzlichen Pflichten.", "Rechtsgrundlagen können Vertrag, vorvertragliche Maßnahmen, Rechtspflicht, berechtigtes Interesse oder erforderliche Einwilligung sein. Die Kenntnisnahme des Datenschutzhinweises ist keine Einwilligung in optionale Werbung oder Analyse."] },
    { id: "access", title: "Zugriff und Empfänger", paragraphs: ["Zugriff ist rollen- und standortbezogen. Plattformadministratoren und Organisationsmanager haben keinen routinemäßigen Zugriff auf Garage-Inhalte. Werkstattpersonal darf Servicedaten nur aufgrund einer berechtigten Beziehung nutzen. Kunden können ihre Angaben und angebotene Freigaben verwalten.", "Technische Anbieter können Supabase, Vercel, MXroute, Stripe, SMS-Dienste und Google Maps umfassen. Beim Laden einer Karte kann Google technische Geräte-, Verbindungs- und Anfragedaten erhalten."] },
    { id: "retention", title: "Aufbewahrung und Kontoschließung", paragraphs: ["Daten werden nur so lange wie erforderlich aufbewahrt. Nach bestätigtem Antrag wird das Konto zunächst gesperrt oder deaktiviert. Danach plant der Administrator eine Löschprüfung nach 30 oder 60 Tagen und verfolgt den Termin im Admin-Ticket.", "Löschung gilt nicht uneingeschränkt. Rechnungen, Zahlungs-, Sicherheits-, Streit- oder Garantienachweise können gesetzlich weiter aufbewahrt werden. Sicherungen folgen getrennten kontrollierten Zyklen."] },
    { id: "rights", title: "Ihre Datenschutzrechte", paragraphs: ["Nach DSGVO können Sie Auskunft, Berichtigung, Löschung, Einschränkung, Übertragbarkeit oder Widerspruch verlangen und eine Einwilligung widerrufen. Pitster darf eine verhältnismäßige Identitätsprüfung durchführen.", "Beschwerden sind bei der rumänischen Behörde ANSPDCP oder einer zuständigen Aufsichtsbehörde möglich. Rechte anderer Personen und zwingende Unterlagen bleiben geschützt."] },
    { id: "security", title: "Sicherheit und Aktualisierungen", paragraphs: ["Pitster nutzt Zugriffskontrollen, Datenbankrichtlinien, Rollentrennung, sichere Authentifizierung und Auditprotokolle. Kein Onlinesystem ist völlig risikofrei. Verdachtsfälle sind über das Problemformular zu melden.", "Die Richtlinie kann bei Dienst- oder Rechtsänderungen aktualisiert werden; wesentliche Änderungen erhalten ein neues Wirksamkeitsdatum und gegebenenfalls einen Plattformhinweis."] },
  ], sourcesTitle: "Datenschutzquellen", sources: [sources.gdpr, sources.authority, sources.googlePrivacy] },
  cookies: { ...deCommon, kicker: "Speicher und externe Dienste", title: "Cookie- und externe Dienste-Richtlinie", introduction: "Pitster verwendet derzeit notwendigen Authentifizierungs- und Präferenzspeicher sowie externe Dienste für Kernfunktionen.", sections: [
    { id: "essential", title: "Notwendige Technologien", paragraphs: ["Cookies oder vergleichbarer Browserspeicher sind für sichere Anmeldung, Sitzungen, Sprache, Navigation und die Speicherung der Kenntnisnahme erforderlich. Sie dienen angeforderten Funktionen und dem Kontoschutz."] },
    { id: "maps", title: "Google Maps", paragraphs: ["Google Maps ermöglicht Standortkarten, Adresssuche und geografische Suche. Beim Laden verbindet sich der Browser mit Google. Google kann IP-Adresse, Geräte- und Browserdaten, Anfragen und ähnliche Kennungen nach eigenen Richtlinien verarbeiten.", "Pitster nutzt Google Maps nicht zur Bildung von Werbeprofilen. Googles eigene Verarbeitung wird von Google gesteuert."] },
    { id: "other-services", title: "Weitere externe Dienste", paragraphs: ["Authentifizierung kann notwendige Sitzungscookies verwenden. Stripe verarbeitet Abonnements, MXroute, SMS-Anbieter und die Meta WhatsApp Business Platform liefern Betriebsnachrichten, Vercel stellt Hosting und Sicherheitsinfrastruktur bereit. WhatsApp wird nur nach Zustimmung verwendet und kann je Buchung oder mit STOP deaktiviert werden."] },
    { id: "optional", title: "Werbung und Analyse", paragraphs: ["Pitster setzt derzeit über diesen Hinweis keine optionalen Werbecookies oder verhaltensbezogene Analyse ein. Neue optionale Technologien werden getrennt und, soweit erforderlich, mit echter Einwilligung angeboten. „Ich habe verstanden“ bestätigt nur die Kenntnisnahme."] },
    { id: "controls", title: "Ihre Einstellungen", paragraphs: ["Browser können Speicher löschen oder blockieren; notwendige Sperren können jedoch Anmeldung und Funktionen verhindern. Das Löschen lokalen Speichers setzt Sprache, Navigation und Hinweisbestätigung zurück. Google-Einstellungen werden bei Google oder im Browser verwaltet."] },
    { id: "changes", title: "Änderungen und Fragen", paragraphs: ["Bei neuen Speicherkategorien oder externen Diensten wird diese Richtlinie aktualisiert. Fragen können als Support-Ticket eingereicht werden."] },
  ], sourcesTitle: "Informationen zu externen Diensten", sources: [sources.euCookies, sources.googlePrivacy, sources.googleMaps] },
};

const huCommon = { ...common, effectiveDate: "Hatályos: 2026. augusztus 14.", contentsLabel: "Ezen az oldalon", closureTitle: "Fiók lezárásának kérése", closureDescription: "Írásbeli kérelmet küldhet a biztonságos űrlapon. Az adminisztrátor ellenőrzi a kérelmet, először blokkolja vagy deaktiválja a fiókot, majd 30 vagy 60 napra ütemezi a törlés felülvizsgálatát. A jogi, számlázási, csalásmegelőzési vagy vitás ügyekhez szükséges adatok kezelése elkülönül.", closureAction: "Fióklezárási kérelem indítása", footerTerms: "Feltételek", footerPrivacy: "Adatvédelem", footerCookies: "Cookie-k" };
const hu: Record<LegalDocumentType, LegalDocument> = {
  terms: { ...huCommon, kicker: "Jogi információk", title: "Felhasználási feltételek", introduction: "Ezek a feltételek a Pitstert használó ügyfelekre, szolgáltató szervezetekre, műhelyvezetőkre és látogatókra vonatkoznak.", sections: [
    { id: "platform", title: "A platform és a szerepkörök", paragraphs: ["A Pitster digitális járműszerviz-platform műhelykereséshez, időpontkéréshez és javításkövetéshez. A szolgáltató szervezetek helyszíneket és előfizetéseket kezelnek, a műhelyvezetők pedig csak a hozzájuk rendelt helyszíneket működtetik.", "A Pitster a platformot biztosítja; általában nem maga végzi a diagnosztikát vagy javítást, és nem része az ügyfél és a műhely közötti szervizszerződésnek."] },
    { id: "accounts", title: "Fiókok és jogosult hozzáférés", paragraphs: ["Pontos adatokat kell megadni, a belépési adatokat védeni kell, és csak engedélyezett szerepkör és helyszín használható. Műhelyvezetői fiók csak meghívással hozható létre.", "A feltételezett hozzáférési problémát azonnal jelezni kell. Érzékeny módosítás előtt személyazonosság- vagy jogosultságellenőrzés kérhető."] },
    { id: "appointments", title: "Időpontok, árajánlatok és fizetések", paragraphs: ["A kérés addig nem megerősített, amíg a műhely el nem fogadja, vagy az ügyfél nem fogad el új időpontot. A szolgáltatásokat, díjakat, árajánlatokat, garanciákat és számlákat az érintett szolgáltató kezeli.", "A platform-előfizetések Stripe-on keresztül működnek. A járműmunkák díjáról az ügyfél és a műhely állapodik meg, hacsak a Pitster nem kínál külön fizetési szolgáltatást."] },
    { id: "content", title: "Jármű- és műhelyadatok", paragraphs: ["Az ügyfelek és jogosult szakemberek kötelesek legjobb tudásuk szerint pontos adatot megadni. Szervizadat csak engedélyezett ügyfél-, jármű- vagy szolgáltatási kapcsolat alapján rögzíthető.", "Tilos jogellenes tartalmat, kártékony kódot, jelszót, szükségtelen érzékeny adatot vagy más jogát sértő információt feltölteni."] },
    { id: "external", title: "Külső szolgáltatások", paragraphs: ["A Pitster többek között Supabase, Vercel, Stripe, MXroute, SMS-szolgáltató, Meta WhatsApp Business Platform és Google Maps szolgáltatást használ. Az elérhetőség ezektől is függhet, a WhatsApp és a Google Maps használatára pedig a szolgáltatók feltételei vonatkoznak."] },
    { id: "suspension", title: "Korlátozás, lezárás és felelősség", paragraphs: ["A Pitster a felhasználók védelme, visszaélés vizsgálata, jogi kötelezettség vagy ellenőrzött lezárási kérelem miatt korlátozhat vagy blokkolhat fiókot. A törlésről az Adatvédelmi szabályzat rendelkezik.", "A jog által megengedett mértékben a Pitster nem garantál megszakítás nélküli hozzáférést, műhelyteljesítést vagy független felhasználói adatok pontosságát. A kötelező fogyasztói jogok változatlanok."] },
    { id: "changes", title: "Módosítások és kapcsolat", paragraphs: ["A feltételek a funkciók vagy jogszabályok változásával frissülhetnek. A lényeges változásokról megfelelő értesítés készül. Hivatalos kérés a Kapcsolat oldalon nyújtható be."] },
  ], sourcesTitle: "Kapcsolódó külső feltételek", sources: [sources.googleMaps, sources.googlePrivacy] },
  privacy: { ...huCommon, kicker: "Személyes adatok", title: "Adatvédelmi szabályzat", introduction: "Ez a szabályzat ismerteti, milyen adatot kezel a Pitster, miért, ki férhet hozzá, és hogyan gyakorolhatók a jogok.", sections: [
    { id: "controller", title: "Adatkezelő és kapcsolat", paragraphs: ["A Pitster platform üzemeltetője határozza meg a fiók- és piactéri adatok kezelését. Adatvédelmi kérelem a Kapcsolat oldalon vagy a support@pitster.app címen küldhető. A szolgáltatói szerződésen vagy számlán szereplő szervezet saját adatkezeléséért maga felel."] },
    { id: "data", title: "Kezelt adatok", paragraphs: ["Szerepkörtől függően ide tartozhatnak az azonosító, kapcsolati és hitelesítési adatok, járművek, opcionális VIN és kilométeróra, garázs, időpontok, javítások, árajánlatok, számlák, szerviztörténet, garanciák, szervezeti és műhelyadatok, hozzárendelések, számlázás, támogatási jegyek és biztonsági naplók."], items: ["Az ügyfél által megadott adatok.", "Jogosult szakember szervizadatai.", "Szervezeti, műhely-, számlázási és hozzáférési adatok.", "Biztonsági, kommunikációs és működési technikai adatok."] },
    { id: "purposes", title: "Célok és jogalapok", paragraphs: ["Az adatkezelés célja a fiók, biztonság, időpont, javítási folyamat, szerviztörténet, kommunikáció, előfizetés, visszaélés-megelőzés, támogatás és jogi kötelezettség.", "A jogalap lehet szerződés, szerződéskötés előtti lépés, jogi kötelezettség, jogos érdek vagy szükséges hozzájárulás. A tájékoztató tudomásulvétele nem hozzájárulás opcionális reklámhoz vagy elemzéshez."] },
    { id: "access", title: "Hozzáférés és címzettek", paragraphs: ["A hozzáférés szerepkörhöz és helyszínhez kötött. A platformadminisztrátorok és szervezeti vezetők nem férnek hozzá rutinszerűen az ügyfél garázstartalmához. A műhely szakemberei csak jogosult kapcsolat alapján kezelhetnek szervizadatot. Az ügyfél megtekintheti adatait és kezelheti az elérhető megosztást.", "Technikai szolgáltató lehet a Supabase, Vercel, MXroute, Stripe, SMS-szolgáltató, Meta WhatsApp Business Platform és Google Maps. A WhatsApp csak működési üzenetekhez adott hozzájárulás után használható, és foglalásonként vagy STOP üzenettel kikapcsolható. Térképbetöltéskor a Google technikai eszköz-, kapcsolat- és kérésadatot kaphat."] },
    { id: "retention", title: "Megőrzés és fióklezárás", paragraphs: ["Az adatokat csak a szükséges ideig őrizzük. Ellenőrzött kérelemnél a fiókot először blokkolják vagy deaktiválják. Az adminisztrátor ezután 30 vagy 60 napra ütemezi a törlés felülvizsgálatát, és az adminjegyben követi a határidőt.", "A törlés nem korlátlan jog. Számla-, fizetési, biztonsági, vitás és garanciaadat jogi okból tovább megőrizhető. A mentések külön ellenőrzött ciklusban járnak le."] },
    { id: "rights", title: "Adatvédelmi jogok", paragraphs: ["A GDPR alapján hozzáférés, helyesbítés, törlés, korlátozás, hordozhatóság vagy tiltakozás kérhető, és a hozzájárulás visszavonható. A Pitster arányos személyazonosság-ellenőrzést kérhet.", "Panasz az ANSPDCP-nél vagy más illetékes felügyeleti hatóságnál tehető. Mások jogai és a kötelező nyilvántartások védelme megmarad."] },
    { id: "security", title: "Biztonság és frissítések", paragraphs: ["A Pitster hozzáférés-vezérlést, adatbázis-szabályokat, szerepkör-szétválasztást, biztonságos hitelesítést és auditot használ. Nincs teljesen kockázatmentes online rendszer. A gyanús eseteket a hibabejelentőn kell jelezni.", "A szabályzat szolgáltatási vagy jogi változáskor frissülhet; a lényeges módosítás új hatálybalépési dátumot és szükség esetén platformértesítést kap."] },
  ], sourcesTitle: "Adatvédelmi hivatkozások", sources: [sources.gdpr, sources.authority, sources.googlePrivacy] },
  cookies: { ...huCommon, kicker: "Tárolás és külső szolgáltatások", title: "Cookie- és külsőszolgáltatás-szabályzat", introduction: "A Pitster jelenleg alapvető hitelesítési és beállítástárolást, valamint a fő funkciókhoz szükséges külső szolgáltatásokat használ.", sections: [
    { id: "essential", title: "Alapvető technológiák", paragraphs: ["Cookie vagy hasonló böngészőtárolás szükséges a biztonságos belépéshez, munkamenethez, nyelvhez, navigációhoz és a tájékoztató tudomásulvételéhez. Ezek a kért funkciókat és a fiókvédelmet szolgálják."] },
    { id: "maps", title: "Google Maps", paragraphs: ["A Google Maps helyszíntérképet, címkeresést és földrajzi keresést biztosít. Betöltéskor a böngésző kapcsolódik a Google-höz, amely saját szabályzata szerint IP-címet, eszköz- és böngészőadatot, kérést és hasonló azonosítót kezelhet.", "A Pitster nem használja a Google Mapset reklámprofil készítésére. A Google saját adatkezelését a Google irányítja."] },
    { id: "other-services", title: "Más külső szolgáltatások", paragraphs: ["A hitelesítés alapvető munkamenet-cookie-t használhat. A Stripe előfizetést, az MXroute, az SMS-szolgáltatók és a Meta WhatsApp Business Platform működési üzenetet, a Vercel tárhelyet és biztonsági infrastruktúrát biztosít."] },
    { id: "optional", title: "Reklám és elemzés", paragraphs: ["A Pitster jelenleg e tájékoztató keretében nem használ opcionális reklámcookie-t vagy viselkedéselemzést. Új opcionális technológia külön, szükség esetén valódi hozzájárulási választással jelenik meg. Az „Értem” csak az olvasást rögzíti."] },
    { id: "controls", title: "Beállítási lehetőségek", paragraphs: ["A böngésző törölheti vagy blokkolhatja a tárolást, de az alapvető tárolás blokkolása megakadályozhatja a belépést. A helyi tár törlése visszaállítja a nyelvet, navigációt és tájékoztató-beállítást. A Google beállításai a Google-nél vagy a böngészőben kezelhetők."] },
    { id: "changes", title: "Változások és kérdések", paragraphs: ["Új tárolási kategória vagy külső szolgáltatás esetén a szabályzat frissül. Kérdés támogatási jegyben küldhető."] },
  ], sourcesTitle: "Külső szolgáltatások információi", sources: [sources.euCookies, sources.googlePrivacy, sources.googleMaps] },
};

export const legalDocuments: Record<Language, Record<LegalDocumentType, LegalDocument>> = { en, de, ro, hu };

export const privacyNoticeCopy: Record<Language, { title: string; paragraphs: string[]; privacyLink: string; cookiesLink: string; action: string }> = {
  en: { title: "Cookies, external services and data privacy", paragraphs: ["Pitster uses technologies required for authentication, security, and appointment functionality. The platform also integrates Google Maps for locating workshops and geographic search. When a map loads, your browser connects to Google services, which may process technical information about your device and connection.", "A customer’s Profile and garage details may contain information entered by service professionals who have an authorised relationship with that customer. Platform administrators and managers do not have routine access to garage content. Customers may view their information, manage available sharing permissions, and request account closure under the Privacy Policy.", "By continuing to use the platform, you confirm that you have read this information. This acknowledgement is not consent to optional advertising or analytics technologies."], privacyLink: "Privacy policy", cookiesLink: "Cookie policy", action: "I understand" },
  de: { title: "Cookies, externe Dienste und Datenschutz", paragraphs: ["Pitster nutzt notwendige Technologien für Anmeldung, Sicherheit und Termine. Google Maps dient der Werkstattsuche und geografischen Suche. Beim Laden einer Karte verbindet sich Ihr Browser mit Google, das technische Geräte- und Verbindungsdaten verarbeiten kann.", "Profil- und Garagendaten können Angaben berechtigter Servicefachkräfte enthalten. Administratoren und Manager haben keinen routinemäßigen Zugriff auf Garage-Inhalte. Kunden können ihre Daten sehen, verfügbare Freigaben verwalten und nach der Datenschutzrichtlinie die Kontoschließung beantragen.", "Mit der weiteren Nutzung bestätigen Sie, diese Information gelesen zu haben. Dies ist keine Einwilligung in optionale Werbung oder Analyse."], privacyLink: "Datenschutzrichtlinie", cookiesLink: "Cookie-Richtlinie", action: "Ich habe verstanden" },
  ro: { title: "Cookie-uri, servicii externe și confidențialitatea datelor", paragraphs: ["Pitster folosește tehnologii necesare autentificării, securității și programărilor. Platforma integrează Google Maps pentru localizarea atelierelor și căutarea geografică. La încărcarea hărții, browserul se conectează la Google, care poate prelucra informații tehnice despre dispozitiv și conexiune.", "Profilul și garajul clientului pot conține informații introduse de profesioniști care au o relație autorizată cu acel client. Administratorii și managerii nu au acces obișnuit la conținutul garajului. Clienții își pot vedea datele, gestiona permisiunile disponibile și solicita închiderea contului conform Politicii de confidențialitate.", "Continuând utilizarea, confirmi că ai citit aceste informații. Confirmarea nu este consimțământ pentru publicitate sau analiză opțională."], privacyLink: "Politica de confidențialitate", cookiesLink: "Politica cookie", action: "Am înțeles" },
  hu: { title: "Cookie-k, külső szolgáltatások és adatvédelem", paragraphs: ["A Pitster a hitelesítéshez, biztonsághoz és időpontokhoz szükséges technológiákat használ. A Google Maps műhelykeresést és földrajzi keresést biztosít. Térképbetöltéskor a böngésző a Google-höz kapcsolódik, amely technikai eszköz- és kapcsolati adatot kezelhet.", "Az ügyfél profilja és garázsa jogosult szervizszakember által rögzített információt is tartalmazhat. Az adminisztrátorok és vezetők nem férnek hozzá rutinszerűen a garázstartalomhoz. Az ügyfél megtekintheti adatait, kezelheti az elérhető megosztást és kérheti a fiók lezárását.", "A platform további használatával megerősíti, hogy elolvasta ezt a tájékoztatást. Ez nem hozzájárulás opcionális reklámhoz vagy elemzéshez."], privacyLink: "Adatvédelmi szabályzat", cookiesLink: "Cookie-szabályzat", action: "Értem" },
};
