"use client";

import Link from "next/link";
import { useActionState } from "react";
import { formatDateTime, locales, translate, type Language, type TranslationKey } from "@/app/i18n";
import { useLanguage } from "@/app/i18n/useLanguage";
import type { ProviderBilling } from "@/lib/dal/provider-billing";
import { openStripePortalAction, startStripeCheckoutAction, updateProviderBillingProfileAction, type ProviderBillingActionState } from "./actions";

const idle: ProviderBillingActionState = { status: "idle" };
const money = (language: Language, cents: number, currency: string) => new Intl.NumberFormat(locales[language], { style: "currency", currency }).format(cents / 100);

export default function ProviderBillingClient({ billing, providers, stripeConfigured, notice, error, logoutAction }: { billing: ProviderBilling; providers: Array<{ id: string; displayName: string }>; stripeConfigured: boolean; notice: string | null; error: string | null; logoutAction: () => Promise<void> }) {
  const [language, setLanguage, ready] = useLanguage();
  const [state, profileAction, pending] = useActionState(updateProviderBillingProfileAction, idle);
  const t = (key: TranslationKey) => translate(language, key);
  if (!ready) return <main className="registration-shell" aria-busy="true" />;
  const hasCustomer = Boolean(billing.subscription.stripeCustomerId);
  return <main className="billing-shell"><header className="settings-topbar"><Link href="/workshop-manager">← {t("workspace.back")}</Link><strong>fixMyRide</strong><select value={language} onChange={(event) => setLanguage(event.target.value as Language)} aria-label={t("a11y.languageSelector")}><option value="en">EN</option><option value="de">DE</option><option value="ro">RO</option><option value="hu">HU</option></select><form action={logoutAction}><button>{t("auth.logout")}</button></form></header><section className="billing-content provider-billing-content"><p className="registration-kicker">{t("providerBilling.eyebrow")}</p><div className="provider-billing-title"><div><h1>{t("providerBilling.title")}</h1><p>{t("providerBilling.description")}</p></div>{providers.length > 1 && <label>{t("providerBilling.provider")}<select value={billing.providerId} onChange={(event) => location.assign(`/workshop-manager/invoicing?providerId=${event.target.value}`)}>{providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.displayName}</option>)}</select></label>}</div>
    {notice === "success" && <p className="note-success">{t("providerBilling.checkoutSuccess")}</p>}{notice === "cancelled" && <p className="note-error">{t("providerBilling.checkoutCancelled")}</p>}{error && <p className="note-error">{t("providerBilling.error")}</p>}
    <section className={`provider-subscription-card subscription-${billing.subscription.status}`}><div><small>{t("providerBilling.plan")}</small><h2>{billing.plan.name}</h2><p>{money(language, billing.plan.monthlyPriceCents, billing.plan.currency)} / {t("providerBilling.month")} · {t("providerBilling.smsIncluded")}</p></div><div><small>{t("providerBilling.status")}</small><strong>{t(`providerBilling.subscription.${billing.subscription.status}` as TranslationKey)}</strong>{billing.subscription.currentPeriodEnd && <span>{t("providerBilling.renews")} {formatDateTime(language, billing.subscription.currentPeriodEnd)}</span>}{billing.subscription.cancelAtPeriodEnd && <span>{t("providerBilling.cancelsAtPeriodEnd")}</span>}</div><div className="provider-subscription-actions">{stripeConfigured && ["not_started", "incomplete_expired", "canceled"].includes(billing.subscription.status) && <form action={startStripeCheckoutAction}><input type="hidden" name="providerId" value={billing.providerId} /><button className="organization-action">{t("providerBilling.subscribe")}</button></form>}{stripeConfigured && hasCustomer && <form action={openStripePortalAction}><input type="hidden" name="providerId" value={billing.providerId} /><button>{t("providerBilling.portal")}</button></form>}{!stripeConfigured && <p className="note-error">{t("providerBilling.notConfigured")}</p>}</div></section>
    <details className="billing-accordion" open><summary><span><strong>{t("providerBilling.profileTitle")}</strong><small>{t("providerBilling.profileDescription")}</small></span></summary><form className="provider-billing-profile" action={profileAction}><input type="hidden" name="providerId" value={billing.providerId} /><label>{t("providerBilling.billingEmail")}<input name="billingEmail" type="email" defaultValue={billing.billingProfile.billingEmail ?? ""} /></label><label>{t("providerBilling.billingContact")}<input name="billingContact" defaultValue={billing.billingProfile.billingContact ?? ""} /></label><label>{t("providerBilling.taxIdentifier")}<input name="taxIdentifier" defaultValue={billing.billingProfile.taxIdentifier ?? ""} /></label><label>{t("providerBilling.addressLine1")}<input name="addressLine1" defaultValue={billing.billingProfile.addressLine1 ?? ""} /></label><label>{t("providerBilling.addressLine2")}<input name="addressLine2" defaultValue={billing.billingProfile.addressLine2 ?? ""} /></label><label>{t("providerBilling.city")}<input name="city" defaultValue={billing.billingProfile.city ?? ""} /></label><label>{t("providerBilling.postalCode")}<input name="postalCode" defaultValue={billing.billingProfile.postalCode ?? ""} /></label><label>{t("providerBilling.country")}<input name="countryCode" minLength={2} maxLength={2} defaultValue={billing.billingProfile.countryCode} required /></label><button disabled={pending}>{t(pending ? "workspace.saving" : "workspace.save")}</button>{state.status !== "idle" && <p className={state.status === "saved" ? "note-success" : "note-error"}>{t(`providerBilling.result.${state.status}` as TranslationKey)}</p>}</form></details>
    <section className="provider-invoices"><h2>{t("providerBilling.invoices")}</h2>{billing.invoices.length ? <div className="billing-table-wrap"><table><thead><tr><th>{t("providerBilling.invoice")}</th><th>{t("providerBilling.period")}</th><th>{t("providerBilling.status")}</th><th>{t("providerBilling.amount")}</th><th>{t("providerBilling.documents")}</th></tr></thead><tbody>{billing.invoices.map((invoice) => <tr key={invoice.id}><td>{invoice.number ?? "—"}</td><td>{invoice.periodStart ? formatDateTime(language, invoice.periodStart) : "—"}</td><td>{invoice.status}</td><td>{money(language, invoice.amountDueCents, invoice.currency)}</td><td>{invoice.hostedInvoiceUrl && <a href={invoice.hostedInvoiceUrl} target="_blank" rel="noreferrer">{t("providerBilling.view")}</a>}{invoice.invoicePdfUrl && <a href={invoice.invoicePdfUrl} target="_blank" rel="noreferrer">PDF</a>}</td></tr>)}</tbody></table></div> : <p className="catalogue-empty">{t("providerBilling.noInvoices")}</p>}</section>
  </section></main>;
}
