"use client";

import Link from "next/link";
import { useActionState, useMemo, useState } from "react";
import { locales, translate, type Language, type TranslationKey } from "@/app/i18n";
import { useLanguage } from "@/app/i18n/useLanguage";
import type { WorkshopInventory, WorkshopInventoryItem, WorkshopInventoryMovement, WorkshopInventoryMovementType, WorkshopInventoryUnit } from "@/lib/dal/workshop-inventory";
import { adjustInventoryStockAction, createInventoryItemAction, importInventoryCsvAction, updateInventoryItemAction, type InventoryActionState } from "./actions";

type Translate = (key: TranslationKey) => string;
type StockFilter = "all" | "available" | "low" | "out";
const idle: InventoryActionState = { status: "idle" };
const units: WorkshopInventoryUnit[] = ["piece", "litre", "kilogram", "set", "pack"];
const movementTypes: WorkshopInventoryMovementType[] = ["received", "used", "corrected", "returned"];
const noItems: WorkshopInventoryItem[] = [];

function stockState(item: WorkshopInventoryItem): Exclude<StockFilter, "all"> { if (item.quantity === 0) return "out"; if (item.minimumQuantity > 0 && item.quantity <= item.minimumQuantity) return "low"; return "available"; }
function quantityText(language: Language, value: number, unit: WorkshopInventoryUnit, t: Translate) { return `${new Intl.NumberFormat(locales[language], { maximumFractionDigits: 2 }).format(value)} ${t(`inventory.unit.${unit}` as TranslationKey)}`; }
function moneyText(language: Language, cents: number | null, currency: string) { return cents === null ? "-" : new Intl.NumberFormat(locales[language], { style: "currency", currency }).format(cents / 100); }

function Result({ state, t }: { state: InventoryActionState; t: Translate }) {
  if (state.status === "idle") return null;
  const success = ["created", "saved", "adjusted", "imported"].includes(state.status);
  return <p role="status" className={success ? "note-success" : "note-error"}>{t(`inventory.status.${state.status}` as TranslationKey)}{state.status === "imported" && state.count ? ` (${state.count})` : ""}</p>;
}

function InventoryFields({ item, t }: { item?: WorkshopInventoryItem; t: Translate }) {
  return <div className="inventory-form-fields">
    <label className="inventory-field-wide">{t("inventory.itemName")}<input name="itemName" defaultValue={item?.itemName} minLength={2} maxLength={160} required /></label>
    <label>{t("inventory.sku")}<input name="sku" defaultValue={item?.sku} maxLength={80} required /></label>
    <label>{t("inventory.oemCode")}<input name="oemCode" defaultValue={item?.oemCode ?? ""} maxLength={100} /></label>
    <label>{t("inventory.type")}<select name="itemType" defaultValue={item?.itemType ?? "part"}><option value="part">{t("inventory.type.part")}</option><option value="consumable">{t("inventory.type.consumable")}</option></select></label>
    {item ? <label>{t("inventory.quantity")}<input value={item.quantity} readOnly aria-describedby="inventory-quantity-help" /><small id="inventory-quantity-help">{t("inventory.quantityAdjustmentHelp")}</small><input type="hidden" name="quantity" value={item.quantity} /></label> : <label>{t("inventory.openingQuantity")}<input name="quantity" type="number" min={0} max={100000000} step="0.01" defaultValue={0} required /></label>}
    <label>{t("inventory.lowStockThreshold")}<input name="minimumQuantity" type="number" min={0} max={100000000} step="0.01" defaultValue={item?.minimumQuantity ?? 0} required /></label>
    <label>{t("inventory.unit")}<select name="unit" defaultValue={item?.unit ?? "piece"}>{units.map((unit) => <option value={unit} key={unit}>{t(`inventory.unit.${unit}` as TranslationKey)}</option>)}</select></label>
    <label>{t("inventory.manufacturer")}<input name="manufacturer" defaultValue={item?.manufacturer ?? ""} maxLength={120} /></label>
    <label>{t("inventory.supplier")}<input name="supplier" defaultValue={item?.supplier ?? ""} maxLength={160} /></label>
    <label>{t("inventory.purchasePrice")}<input name="purchasePrice" type="number" min={0} max={1000000000} step="0.01" defaultValue={item?.purchasePriceCents == null ? "" : item.purchasePriceCents / 100} /></label>
    <label>{t("inventory.sellingPrice")}<input name="sellingPrice" type="number" min={0} max={1000000000} step="0.01" defaultValue={item?.sellingPriceCents == null ? "" : item.sellingPriceCents / 100} /></label>
    <label>{t("inventory.currency")}<input name="currency" defaultValue={item?.currency ?? "EUR"} minLength={3} maxLength={3} required /></label>
    <label>{t("inventory.storageLocation")}<input name="storageLocation" defaultValue={item?.storageLocation ?? ""} maxLength={120} placeholder={t("inventory.storageLocationPlaceholder")} /></label>
    <label className="inventory-field-wide">{t("inventory.vehicleApplication")}<input name="vehicleApplication" defaultValue={item?.vehicleApplication ?? ""} maxLength={240} placeholder={t("inventory.vehicleApplicationPlaceholder")} /></label>
    <label className="inventory-field-wide">{t("inventory.notes")}<textarea name="notes" defaultValue={item?.notes ?? ""} rows={3} maxLength={1000} /></label>
  </div>;
}

function DialogShell({ eyebrow, title, closeLabel, onClose, children }: { eyebrow: string; title: string; closeLabel: string; onClose: () => void; children: React.ReactNode }) {
  return <div className="inventory-editor-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="inventory-editor" role="dialog" aria-modal="true" aria-label={title}><header><div><p>{eyebrow}</p><h2>{title}</h2></div><button type="button" onClick={onClose} aria-label={closeLabel}>&times;</button></header>{children}</section></div>;
}

function InventoryEditor({ workshopId, item, t, onClose }: { workshopId: string; item: WorkshopInventoryItem | null; t: Translate; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(item ? updateInventoryItemAction : createInventoryItemAction, idle);
  return <DialogShell eyebrow={t(item ? "inventory.editEyebrow" : "inventory.addEyebrow")} title={t(item ? "inventory.editTitle" : "inventory.addTitle")} closeLabel={t("inventory.close")} onClose={onClose}><form action={formAction}>{item ? <input type="hidden" name="inventoryId" value={item.id} /> : <input type="hidden" name="workshopId" value={workshopId} />}<fieldset disabled={pending}><InventoryFields item={item ?? undefined} t={t} /></fieldset><Result state={state} t={t} /><footer><button type="button" className="inventory-secondary-action" onClick={onClose}>{t("inventory.cancel")}</button><button disabled={pending}>{t(pending ? "inventory.saving" : item ? "inventory.save" : "inventory.add")}</button></footer></form></DialogShell>;
}

function StockAdjustment({ item, t, onClose }: { item: WorkshopInventoryItem; t: Translate; onClose: () => void }) {
  const [type, setType] = useState<WorkshopInventoryMovementType>("received"); const [state, formAction, pending] = useActionState(adjustInventoryStockAction, idle);
  return <DialogShell eyebrow={t("inventory.adjustEyebrow")} title={`${t("inventory.adjustStock")}: ${item.itemName}`} closeLabel={t("inventory.close")} onClose={onClose}><form action={formAction}><input type="hidden" name="inventoryId" value={item.id} /><div className="inventory-adjust-summary"><span>{t("inventory.currentStock")}</span><strong>{item.quantity} {t(`inventory.unit.${item.unit}` as TranslationKey)}</strong></div><fieldset disabled={pending} className="inventory-adjust-fields"><div className="inventory-movement-tabs">{movementTypes.map((movement) => <label key={movement} className={type === movement ? "active" : ""}><input type="radio" name="movementType" value={movement} checked={type === movement} onChange={() => setType(movement)} />{t(`inventory.movement.${movement}` as TranslationKey)}</label>)}</div><label>{t(type === "corrected" ? "inventory.countedQuantity" : "inventory.adjustQuantity")}<input name="quantity" type="number" min={0} max={100000000} step="0.01" required /></label><label>{t("inventory.reference")}<input name="reference" maxLength={120} placeholder={t("inventory.referencePlaceholder")} /></label><label className="inventory-field-wide">{t("inventory.reason")}<textarea name="reason" maxLength={240} rows={3} /></label></fieldset><p className="inventory-adjust-help">{t(`inventory.movementHelp.${type}` as TranslationKey)}</p><Result state={state} t={t} /><footer><button type="button" className="inventory-secondary-action" onClick={onClose}>{t("inventory.cancel")}</button><button disabled={pending}>{t(pending ? "inventory.saving" : "inventory.applyAdjustment")}</button></footer></form></DialogShell>;
}

function CsvImport({ workshopId, t, onClose }: { workshopId: string; t: Translate; onClose: () => void }) {
  const [state, formAction, pending] = useActionState(importInventoryCsvAction, idle);
  return <DialogShell eyebrow={t("inventory.csvEyebrow")} title={t("inventory.importCsv")} closeLabel={t("inventory.close")} onClose={onClose}><form action={formAction}><input type="hidden" name="workshopId" value={workshopId} /><div className="inventory-import-guide"><p>{t("inventory.importDescription")}</p><code>itemName, sku, oemCode, itemType, quantity, minimumQuantity, unit, manufacturer, vehicleApplication, supplier, purchasePrice, sellingPrice, currency, storageLocation, notes</code></div><label className="inventory-file-field">{t("inventory.csvFile")}<input name="csvFile" type="file" accept=".csv,text/csv" required /></label><Result state={state} t={t} /><footer><button type="button" className="inventory-secondary-action" onClick={onClose}>{t("inventory.cancel")}</button><button disabled={pending}>{t(pending ? "inventory.importing" : "inventory.importCsv")}</button></footer></form></DialogShell>;
}

function StockHistory({ item, movements, language, t, onClose }: { item: WorkshopInventoryItem; movements: WorkshopInventoryMovement[]; language: Language; t: Translate; onClose: () => void }) {
  return <DialogShell eyebrow={t("inventory.historyEyebrow")} title={`${t("inventory.stockHistory")}: ${item.itemName}`} closeLabel={t("inventory.close")} onClose={onClose}><div className="inventory-history">{movements.length ? movements.map((movement) => <article key={movement.id}><div><span className={`inventory-movement-badge ${movement.movementType}`}>{t(`inventory.movement.${movement.movementType}` as TranslationKey)}</span><time>{new Intl.DateTimeFormat(locales[language], { dateStyle: "medium", timeStyle: "short" }).format(new Date(movement.createdAt))}</time></div><strong>{movement.quantityChange > 0 ? "+" : ""}{quantityText(language, movement.quantityChange, movement.unit, t)}</strong><p>{quantityText(language, movement.previousQuantity, movement.unit, t)} &rarr; {quantityText(language, movement.newQuantity, movement.unit, t)}</p>{movement.reason && <p>{movement.reason}</p>}<small>{movement.actorName}{movement.reference ? ` · ${movement.reference}` : ""}</small></article>) : <p>{t("inventory.noHistory")}</p>}</div></DialogShell>;
}

export default function WorkshopInventoryClient({ inventories, movements, logoutAction, portalBasePath }: { inventories: WorkshopInventory[]; movements: Record<string, WorkshopInventoryMovement[]>; logoutAction: () => Promise<void>; portalBasePath: "/workshop-manager" | "/service-organisation" }) {
  const [language, setLanguage, ready] = useLanguage(); const t = (key: TranslationKey) => translate(language, key);
  const [workshopId, setWorkshopId] = useState(inventories[0]?.workshopId ?? ""); const [query, setQuery] = useState(""); const [typeFilter, setTypeFilter] = useState<"all" | "part" | "consumable">("all"); const [stockFilter, setStockFilter] = useState<StockFilter>("all");
  const [editing, setEditing] = useState<"new" | WorkshopInventoryItem | null>(null); const [adjusting, setAdjusting] = useState<WorkshopInventoryItem | null>(null); const [historyItem, setHistoryItem] = useState<WorkshopInventoryItem | null>(null); const [importing, setImporting] = useState(false);
  const inventory = inventories.find((entry) => entry.workshopId === workshopId) ?? inventories[0]; const items = inventory?.items ?? noItems;
  const visibleItems = useMemo(() => { const needle = query.trim().toLocaleLowerCase(language); return items.filter((item) => { const haystack = [item.itemName, item.sku, item.oemCode, item.manufacturer, item.vehicleApplication, item.supplier, item.storageLocation].filter(Boolean).join(" ").toLocaleLowerCase(language); return (!needle || haystack.includes(needle)) && (typeFilter === "all" || item.itemType === typeFilter) && (stockFilter === "all" || stockState(item) === stockFilter); }); }, [items, language, query, stockFilter, typeFilter]);
  const lowCount = items.filter((item) => stockState(item) === "low").length; const outCount = items.filter((item) => stockState(item) === "out").length; const attentionCount = lowCount + outCount;
  if (!ready) return <main className="registration-shell" aria-busy="true" />;
  return <main className="settings-shell inventory-shell"><header className="settings-topbar"><Link href={portalBasePath}>&larr; {t("workspace.back")}</Link><strong>pitster</strong><select value={language} onChange={(event) => setLanguage(event.target.value as Language)} aria-label={t("a11y.languageSelector")}><option value="en">EN</option><option value="de">DE</option><option value="ro">RO</option><option value="hu">HU</option></select><form action={logoutAction}><button>{t("auth.logout")}</button></form></header><section className="settings-content inventory-content"><header className="inventory-title"><div><p className="registration-kicker">{t("inventory.eyebrow")}</p><h1>{t("inventory.title")}</h1><span>{t("inventory.description")}</span></div>{inventory && <div className="inventory-title-actions"><button type="button" className="inventory-secondary-button" onClick={() => setImporting(true)}>{t("inventory.importCsv")}</button><Link href={`/api/inventory/${inventory.workshopId}/export`}>{t("inventory.exportCsv")}</Link><Link href={`/api/inventory/${inventory.workshopId}/stocktake`}>{t("inventory.printStocktake")}</Link><button type="button" onClick={() => setEditing("new")}>+ {t("inventory.add")}</button></div>}</header>
  {inventory ? <>{attentionCount > 0 && <button className="inventory-warning" type="button" onClick={() => setStockFilter(attentionCount === outCount ? "out" : "low")}><strong>{t("inventory.attentionTitle")}</strong><span>{t("inventory.attentionDescription")} ({attentionCount})</span></button>}<div className="inventory-overview"><article><span>{t("inventory.totalItems")}</span><strong>{items.length}</strong></article><article className={lowCount ? "attention" : ""}><span>{t("inventory.lowStock")}</span><strong>{lowCount}</strong></article><article className={outCount ? "danger" : ""}><span>{t("inventory.outOfStock")}</span><strong>{outCount}</strong></article></div>
  <div className="inventory-filters"><label className="inventory-search">{t("inventory.search")}<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("inventory.searchPlaceholder")} /></label>{inventories.length > 1 && <label>{t("inventory.workshop")}<select value={inventory.workshopId} onChange={(event) => { setWorkshopId(event.target.value); setEditing(null); }}><option value={inventory.workshopId}>{inventory.workshopName}</option>{inventories.filter((entry) => entry.workshopId !== inventory.workshopId).map((entry) => <option value={entry.workshopId} key={entry.workshopId}>{entry.workshopName}</option>)}</select></label>}<label>{t("inventory.type")}<select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value as typeof typeFilter)}><option value="all">{t("inventory.filter.allTypes")}</option><option value="part">{t("inventory.type.part")}</option><option value="consumable">{t("inventory.type.consumable")}</option></select></label><label>{t("inventory.stock")}<select value={stockFilter} onChange={(event) => setStockFilter(event.target.value as StockFilter)}><option value="all">{t("inventory.filter.allStock")}</option><option value="available">{t("inventory.stock.available")}</option><option value="low">{t("inventory.stock.low")}</option><option value="out">{t("inventory.stock.out")}</option></select></label></div>
  <section className="inventory-table-card" aria-labelledby="inventory-workshop-title"><header><div><p>{inventory.serviceProviderName}</p><h2 id="inventory-workshop-title">{inventory.workshopName}</h2></div><span>{visibleItems.length} {t("inventory.visibleItems")}</span></header><div className="inventory-table-wrap"><table><thead><tr><th>{t("inventory.itemName")}</th><th>{t("inventory.sku")}</th><th>{t("inventory.type")}</th><th>{t("inventory.quantity")}</th><th>{t("inventory.supplier")}</th><th>{t("inventory.prices")}</th><th>{t("inventory.vehicleApplication")}</th><th>{t("inventory.stock")}</th><th>{t("inventory.actions")}</th></tr></thead><tbody>{visibleItems.map((item) => { const state = stockState(item); return <tr key={item.id} className={`inventory-stock-${state}`}><td><strong>{item.itemName}</strong><small>{item.storageLocation || t("inventory.noBin")}</small></td><td><code>{item.sku}</code><small>{item.oemCode ?? "-"}</small></td><td>{t(`inventory.type.${item.itemType}` as TranslationKey)}</td><td><b>{quantityText(language, item.quantity, item.unit, t)}</b>{item.minimumQuantity > 0 && <small>{t("inventory.minimumShort")} {quantityText(language, item.minimumQuantity, item.unit, t)}</small>}</td><td>{item.supplier ?? "-"}</td><td><b>{moneyText(language, item.purchasePriceCents, item.currency)}</b><small>{t("inventory.sellShort")} {moneyText(language, item.sellingPriceCents, item.currency)}</small></td><td>{item.vehicleApplication ?? t("inventory.allVehicles")}</td><td><span className={`inventory-stock-badge ${state}`}>{t(`inventory.stock.${state}` as TranslationKey)}</span></td><td><div className="inventory-row-actions"><button type="button" className="primary" onClick={() => setAdjusting(item)}>{t("inventory.adjust")}</button><button type="button" onClick={() => setHistoryItem(item)}>{t("inventory.history")}</button><button type="button" onClick={() => setEditing(item)}>{t("inventory.edit")}</button></div></td></tr>; })}</tbody></table></div>{!visibleItems.length && <div className="inventory-empty"><h3>{items.length ? t("inventory.noMatchesTitle") : t("inventory.emptyTitle")}</h3><p>{items.length ? t("inventory.noMatchesDescription") : t("inventory.emptyDescription")}</p>{!items.length && <button type="button" onClick={() => setEditing("new")}>+ {t("inventory.addFirst")}</button>}</div>}</section></> : <div className="catalogue-empty"><h2>{t("inventory.noWorkshopTitle")}</h2><p>{t("inventory.noWorkshopDescription")}</p><Link className="organization-action" href={portalBasePath === "/service-organisation" ? "/service-organisation/locations" : "/workshop-manager/workshops"}>{t("inventory.manageWorkshops")}</Link></div>}</section>
  {inventory && editing && <InventoryEditor workshopId={inventory.workshopId} item={editing === "new" ? null : editing} t={t} onClose={() => setEditing(null)} />}{adjusting && <StockAdjustment item={adjusting} t={t} onClose={() => setAdjusting(null)} />}{historyItem && <StockHistory item={historyItem} movements={(movements[inventory?.workshopId ?? ""] ?? []).filter((movement) => movement.inventoryId === historyItem.id)} language={language} t={t} onClose={() => setHistoryItem(null)} />}{inventory && importing && <CsvImport workshopId={inventory.workshopId} t={t} onClose={() => setImporting(false)} />}</main>;
}
