"use client";

import Link from "@/app/WorkspaceLink";
import { useMemo, useState } from "react";
import { locales, translate, type Language, type TranslationKey } from "@/app/i18n";
import { useLanguage } from "@/app/i18n/useLanguage";
import ProviderOnboardingChecklist from "@/app/guidance/ProviderOnboardingChecklist";
import ProviderRecommendations from "@/app/guidance/ProviderRecommendations";
import type { ManagedServiceProvider } from "@/lib/dal/service-providers";
import type { OrganisationLocationMetric, ServiceOrganisationOperationalDashboard, ServiceOrganisationQualityMetrics } from "@/lib/dal/service-organisation-dashboard";
import type { ProviderOnboardingSummary } from "@/lib/provider-onboarding";
import type { ProviderRecommendation } from "@/lib/provider-recommendations";

type Translate = (key: TranslationKey) => string;
function money(language: Language, revenue: Record<string, number>) { const entries = Object.entries(revenue); return entries.length ? entries.map(([currency, cents]) => new Intl.NumberFormat(locales[language], { style: "currency", currency, maximumFractionDigits: 0 }).format(cents / 100)).join(" · ") : "-"; }
function hours(minutes: number, language: Language) { return new Intl.NumberFormat(locales[language], { maximumFractionDigits: 1 }).format(minutes / 60); }
function rating(value: number | null, count: number, t: Translate) { return value === null ? t("organisationDashboard.noRatings") : `${value.toFixed(1)} / 5 (${count})`; }

function LocationComparison({ locations, language, t }: { locations: OrganisationLocationMetric[]; language: Language; t: Translate }) {
  const maxAppointments = Math.max(1, ...locations.map((location) => location.appointments)); const maxWorkload = Math.max(1, ...locations.map((location) => location.workloadMinutes));
  return <section className="organisation-comparison"><header><div><p>{t("organisationDashboard.comparisonEyebrow")}</p><h2>{t("organisationDashboard.comparisonTitle")}</h2></div><span>{locations.length} {t("organisationDashboard.locations")}</span></header><div className="organisation-comparison-list">{locations.map((location) => <article key={location.id}><div className="organisation-location-name"><strong>{location.name}</strong><small>{location.city ?? t("organisationDashboard.cityUnavailable")}</small></div><div className="organisation-bar-metric"><span>{t("organisationDashboard.appointments")}</span><b style={{ width: `${Math.max(4, location.appointments / maxAppointments * 100)}%` }} /><strong>{location.appointments}</strong></div><div className="organisation-bar-metric"><span>{t("organisationDashboard.workload")}</span><b style={{ width: `${Math.max(4, location.workloadMinutes / maxWorkload * 100)}%` }} /><strong>{hours(location.workloadMinutes, language)} h</strong></div><div className="organisation-location-revenue"><span>{t("organisationDashboard.revenue")}</span><strong>{money(language, location.revenueByCurrency)}</strong></div></article>)}</div></section>;
}

export default function ServiceOrganisationDashboard({ displayName, providers, lowStockCount, dashboards, qualityMetrics, onboarding, recommendations, logoutAction }: { displayName: string; providers: ManagedServiceProvider[]; lowStockCount: number; dashboards: Record<string, ServiceOrganisationOperationalDashboard>; qualityMetrics: Record<string, ServiceOrganisationQualityMetrics>; onboarding: Record<string, ProviderOnboardingSummary>; recommendations: Record<string, ProviderRecommendation[]>; logoutAction: () => Promise<void> }) {
  const [language, setLanguage, ready] = useLanguage(); const t = (key: TranslationKey) => translate(language, key);
  const [providerId, setProviderId] = useState(providers[0]?.id ?? ""); const dashboard = dashboards[providerId] ?? dashboards[providers[0]?.id];
  const quality = qualityMetrics[providerId] ?? qualityMetrics[providers[0]?.id];
  const selectedOnboarding = onboarding[providerId] ?? onboarding[providers[0]?.id];
  const selectedRecommendations = recommendations[providerId] ?? recommendations[providers[0]?.id] ?? [];
  const totals = useMemo(() => dashboard ? dashboard.locations.reduce((value, location) => ({ appointments: value.appointments + location.appointments, activeJobs: value.activeJobs + location.activeJobs, workloadMinutes: value.workloadMinutes + location.workloadMinutes, revenue: Object.fromEntries([...new Set([...Object.keys(value.revenue), ...Object.keys(location.revenueByCurrency)])].map((currency) => [currency, (value.revenue[currency] ?? 0) + (location.revenueByCurrency[currency] ?? 0)])) }), { appointments: 0, activeJobs: 0, workloadMinutes: 0, revenue: {} as Record<string, number> }) : null, [dashboard]);
  const monthLabel = new Intl.DateTimeFormat(locales[language], { month: "long", year: "numeric" }).format(new Date());
  if (!ready) return <main className="registration-shell" aria-busy="true" />;
  return <main className="organization-shell organisation-dashboard-shell"><header className="organization-topbar"><strong>pitster</strong><select value={language} onChange={(event) => setLanguage(event.target.value as Language)} aria-label={t("a11y.languageSelector")}><option value="en">EN</option><option value="de">DE</option><option value="ro">RO</option><option value="hu">HU</option></select><form action={logoutAction}><button>{t("auth.logout")}</button></form></header><section className="organization-content organisation-dashboard-content"><header className="organisation-dashboard-hero"><div><p className="registration-kicker">{t("organisationDashboard.eyebrow")}</p><h1>{t("serviceOrganisationPortal.welcome").replace("{name}", displayName)}</h1><span>{t("organisationDashboard.description")}</span></div><div><label>{t("organisationDashboard.organisation")}<select value={providerId} onChange={(event) => setProviderId(event.target.value)}>{providers.map((provider) => <option value={provider.id} key={provider.id}>{provider.displayName}</option>)}</select></label><strong>{monthLabel}</strong></div></header>
  <nav className="manager-portal-links"><Link className="organization-action" href="/service-organisation/requests">{t("workshopBookings.title")}</Link><Link className="organization-action" href="/service-organisation/repairs">{t("repairLifecycle.title")}</Link><Link className="organization-action" href="/service-organisation/quality">{t("quality.title")}</Link><Link className="organization-action" href="/service-organisation/locations">{t("serviceOrganisationPortal.locations")}</Link><Link className="organization-action" href="/service-organisation/services">{t("serviceCatalogue.title")}</Link><Link className="organization-action" href="/service-organisation/managers">{t("serviceOrganisationPortal.managers")}</Link><Link className="organization-action" href="/service-organisation/inventory">{t("inventory.title")}</Link><Link className="organization-action" href="/service-organisation/billing">{t("serviceOrganisationPortal.billing")}</Link><Link className="organization-action" href="/service-organisation/settings">{t("roleSidebar.nav.organisationSettings")}</Link></nav>
  {selectedOnboarding && <ProviderOnboardingChecklist role="service_organisation" summary={selectedOnboarding} language={language} />}
  <ProviderRecommendations recommendations={selectedRecommendations} language={language} />
  {lowStockCount > 0 && <Link className="dashboard-stock-warning" href="/service-organisation/inventory"><strong>{t("inventory.attentionTitle")}</strong><span>{t("inventory.attentionDescription")} ({lowStockCount})</span></Link>}
  {dashboard && totals ? <><section className="organisation-kpis"><article><span>{t("organisationDashboard.appointments")}</span><strong>{totals.appointments}</strong><small>{dashboard.locations.length} {t("organisationDashboard.locations")}</small></article><article><span>{t("organisationDashboard.revenue")}</span><strong>{money(language, totals.revenue)}</strong><small>{t("organisationDashboard.invoicedThisMonth")}</small></article><article><span>{t("organisationDashboard.activeJobs")}</span><strong>{totals.activeJobs}</strong><small>{hours(totals.workloadMinutes, language)} {t("organisationDashboard.workloadHours")}</small></article><article className={dashboard.overdueJobs.length ? "attention" : ""}><span>{t("organisationDashboard.overdueJobs")}</span><strong>{dashboard.overdueJobs.length}</strong><small>{dashboard.openEstimates.length} {t("organisationDashboard.openEstimates")}</small></article></section>
  <LocationComparison locations={dashboard.locations} language={language} t={t} />
  {quality && <section className="organisation-quality-summary"><header><div><p>{t("organisationDashboard.qualityEyebrow")}</p><h2>{t("organisationDashboard.qualityTitle")}</h2><span>{t("organisationDashboard.qualityDescription")}</span></div><Link href="/workshop-manager/quality">{t("organisationDashboard.openQuality")}</Link></header><div><article><span>{t("organisationDashboard.openWarrantyCases")}</span><strong>{quality.openCases}</strong></article><article><span>{t("organisationDashboard.resolvedWarrantyCases")}</span><strong>{quality.resolvedCases}</strong></article><article><span>{t("organisationDashboard.comebackRate")}</span><strong>{quality.comebackRate.toFixed(1)}%</strong></article></div><ul>{quality.locations.map((location) => <li key={location.workshopId}><span>{location.workshopName}</span><b>{location.openCases} / {location.totalCases}</b></li>)}</ul></section>}
  <section className="organisation-location-table"><header><div><p>{t("organisationDashboard.locationDetailEyebrow")}</p><h2>{t("organisationDashboard.locationDetailTitle")}</h2></div></header><div><table><thead><tr><th>{t("organisationDashboard.location")}</th><th>{t("organisationDashboard.appointments")}</th><th>{t("organisationDashboard.workload")}</th><th>{t("organisationDashboard.openEstimates")}</th><th>{t("organisationDashboard.overdueJobs")}</th><th>{t("organisationDashboard.inventoryAlerts")}</th><th>{t("organisationDashboard.satisfaction")}</th><th>{t("organisationDashboard.cancellationRate")}</th></tr></thead><tbody>{dashboard.locations.map((location) => <tr key={location.id}><th><strong>{location.name}</strong><small>{location.city}</small></th><td>{location.appointments}</td><td>{hours(location.workloadMinutes, language)} h</td><td>{location.openEstimates}</td><td className={location.overdueJobs ? "attention" : ""}>{location.overdueJobs}</td><td className={location.inventoryAlerts ? "attention" : ""}>{location.inventoryAlerts}</td><td>{rating(location.averageRating, location.feedbackCount, t)}</td><td>{location.cancellationRate.toFixed(1)}%</td></tr>)}</tbody></table></div></section>
  <section className="organisation-exceptions"><article><header><div><p>{t("organisationDashboard.estimatesEyebrow")}</p><h2>{t("organisationDashboard.openEstimates")}</h2></div><strong>{dashboard.openEstimates.length}</strong></header>{dashboard.openEstimates.length ? dashboard.openEstimates.slice(0, 8).map((estimate) => <div key={estimate.id}><span><strong>{estimate.customerName}</strong><small>{estimate.workshopName} · {estimate.serviceName}</small></span><b>{money(language, { [estimate.currency]: estimate.totalCents })}</b></div>) : <p>{t("organisationDashboard.noOpenEstimates")}</p>}<Link href="/workshop-manager/repairs">{t("organisationDashboard.openRepairs")}</Link></article><article className="overdue"><header><div><p>{t("organisationDashboard.jobsEyebrow")}</p><h2>{t("organisationDashboard.overdueJobs")}</h2></div><strong>{dashboard.overdueJobs.length}</strong></header>{dashboard.overdueJobs.length ? dashboard.overdueJobs.slice(0, 8).map((job) => <div key={job.id}><span><strong>{job.customerName}</strong><small>{job.workshopName} · {job.serviceName}</small></span><b>{t(`workshopBookings.status.${job.status}` as TranslationKey)}</b></div>) : <p>{t("organisationDashboard.noOverdueJobs")}</p>}<Link href="/workshop-manager/requests">{t("organisationDashboard.openCalendar")}</Link></article></section>
  <section className="organisation-monthly-report"><header><div><p>{t("organisationDashboard.reportEyebrow")}</p><h2>{t("organisationDashboard.monthlyReport")}</h2><span>{t("organisationDashboard.reportDescription")}</span></div><Link href={`/api/service-organisation/${dashboard.providerId}/monthly-report`}>{t("organisationDashboard.exportReport")}</Link></header><div><table><thead><tr><th>{t("organisationDashboard.month")}</th><th>{t("organisationDashboard.appointments")}</th><th>{t("organisationDashboard.completedJobs")}</th><th>{t("organisationDashboard.workload")}</th><th>{t("organisationDashboard.revenue")}</th><th>{t("organisationDashboard.cancellationRate")}</th><th>{t("organisationDashboard.satisfaction")}</th></tr></thead><tbody>{dashboard.months.map((month) => <tr key={month.month}><th>{new Intl.DateTimeFormat(locales[language], { month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${month.month}T00:00:00Z`))}</th><td>{month.appointments}</td><td>{month.completedJobs}</td><td>{hours(month.workloadMinutes, language)} h</td><td>{money(language, month.revenueByCurrency)}</td><td>{month.cancellationRate.toFixed(1)}%</td><td>{month.averageRating === null ? "-" : `${month.averageRating.toFixed(1)} / 5`}</td></tr>)}</tbody></table></div></section></> : <div className="catalogue-empty"><h2>{t("organisationDashboard.emptyTitle")}</h2><p>{t("organisationDashboard.emptyDescription")}</p></div>}</section></main>;
}
