"use client";

import Link from "@/app/WorkspaceLink";
import { useActionState, useMemo, useState } from "react";
import { formatDateTime, translate, type Language, type TranslationKey } from "@/app/i18n";
import { useLanguage } from "@/app/i18n/useLanguage";
import type { ManagedQualityWorkspace, MaintenanceDueReminder, QualityJob, WarrantyCase } from "@/lib/dal/workshop-quality";
import { createWarrantyCaseAction, maintenanceOutreachAction, resolveWarrantyCaseAction, saveJobWarrantyAction, type QualityActionState } from "./actions";
import PlatformDateTimeInput from "@/app/PlatformDateTimeInput";

type T = (key: TranslationKey) => string;
const idle: QualityActionState = { status: "idle" };
function Result({ state, t }: { state: QualityActionState; t: T }) { return state.status === "idle" ? null : <p className={["saved", "sent"].includes(state.status) ? "note-success" : "note-error"} role="status">{t(`quality.result.${state.status}` as TranslationKey)}{state.diagnostic ? ` ${state.diagnostic}` : ""}</p>; }

function WarrantySettings({ job, t }: { job: QualityJob; t: T }) {
  const [state, action, pending] = useActionState(saveJobWarrantyAction, idle);
  return <form className="quality-warranty-row" action={action}><input type="hidden" name="bookingId" value={job.id} /><span><strong>{job.vehicleRegistration} · {job.serviceName}</strong><small>{job.workshopName} · {job.customerName}</small></span><label>{t("quality.labourWarranty")}<PlatformDateTimeInput mode="date" name="labourWarrantyExpiresOn" defaultValue={job.labourWarrantyExpiresOn ?? ""} ariaLabel={t("quality.labourWarranty")} /></label><button disabled={pending}>{t("common.save")}</button><Result state={state} t={t} /></form>;
}

function NewCase({ workspace, t }: { workspace: ManagedQualityWorkspace; t: T }) {
  const [state, action, pending] = useActionState(createWarrantyCaseAction, idle);
  const [originalId, setOriginalId] = useState(workspace.originalJobs[0]?.id ?? "");
  const original = workspace.originalJobs.find((job) => job.id === originalId);
  const returns = workspace.returnJobs.filter((job) => job.id !== originalId && (!original || job.workshopId === original.workshopId) && (!original || job.vehicleRegistration.toUpperCase() === original.vehicleRegistration.toUpperCase()));
  const mechanics = workspace.mechanics.filter((mechanic) => !original || mechanic.workshopId === original.workshopId);
  return <form className="quality-case-form" action={action}><header><p>{t("quality.caseEyebrow")}</p><h2>{t("quality.newCase")}</h2></header><div className="quality-case-fields"><label>{t("quality.originalJob")}<select name="originalBookingId" required value={originalId} onChange={(event) => setOriginalId(event.target.value)}>{workspace.originalJobs.map((job) => <option key={job.id} value={job.id}>{job.vehicleRegistration} · {job.serviceName} · {job.workshopName}</option>)}</select></label><label>{t("quality.returnJob")}<select name="returnBookingId" required defaultValue=""><option value="" disabled>{t("quality.chooseReturn")}</option>{returns.map((job) => <option key={job.id} value={job.id}>{job.vehicleRegistration} · {job.serviceName} · {job.customerName}</option>)}</select></label><label>{t("quality.caseType")}<select name="kind"><option value="warranty">{t("quality.kind.warranty")}</option><option value="comeback">{t("quality.kind.comeback")}</option></select></label><label>{t("quality.technician")}<select name="technicianResourceId"><option value="">{t("quality.assignedMechanic")}</option>{mechanics.map((mechanic) => <option key={mechanic.id} value={mechanic.id}>{mechanic.name}</option>)}</select></label></div><label>{t("quality.internalNotes")}<textarea name="internalNotes" rows={3} maxLength={5000} /></label>{returns.length === 0 && original && <p className="note-warning">{t("quality.noMatchingReturn")}</p>}<Result state={state} t={t} /><button className="organization-action" disabled={pending || !returns.length}>{t("quality.createCase")}</button></form>;
}

function CaseCard({ item, language, t }: { item: WarrantyCase; language: Language; t: T }) {
  const [state, action, pending] = useActionState(resolveWarrantyCaseAction, idle);
  return <article className={`quality-case-card status-${item.status}`}><header><span><small>{t(`quality.kind.${item.kind}` as TranslationKey)}</small><strong>{item.vehicleRegistration} · {item.serviceName}</strong><em>{item.workshopName}</em></span><b>{t(`quality.status.${item.status}` as TranslationKey)}</b></header><dl><div><dt>{t("quality.customer")}</dt><dd>{item.customerName}</dd></div><div><dt>{t("quality.originalJob")}</dt><dd>{formatDateTime(language, item.originalCompletedAt)}</dd></div><div><dt>{t("quality.technician")}</dt><dd>{item.technicianName ?? t("quality.unassigned")}</dd></div><div><dt>{t("quality.labourWarranty")}</dt><dd>{item.labourWarrantyExpiresOn ?? t("common.notRecorded")}</dd></div></dl>{item.partsWarranty.length > 0 && <p><b>{t("quality.partsWarranty")}</b> {item.partsWarranty.map((part) => `${part.description}: ${part.expiresOn}`).join(" · ")}</p>}{item.internalNotes && <p><b>{t("quality.internalNotes")}</b> {item.internalNotes}</p>}{item.resolution && <p className="note-success"><b>{t("quality.resolution")}</b> {item.resolution}</p>}{item.status === "open" && <form action={action}><input type="hidden" name="caseId" value={item.id} /><label>{t("quality.resolution")}<textarea name="resolution" rows={3} minLength={2} maxLength={5000} required /></label><label>{t("quality.internalNotesOptional")}<textarea name="internalNotes" rows={2} maxLength={5000} /></label><Result state={state} t={t} /><button disabled={pending}>{t("quality.resolve")}</button></form>}</article>;
}

function Outreach({ reminder, t }: { reminder: MaintenanceDueReminder; t: T }) {
  const [state, action, pending] = useActionState(maintenanceOutreachAction, idle);
  return <article className="quality-reminder-card"><header><span><strong>{reminder.description}</strong><small>{reminder.vehicleRegistration} · {reminder.vehicleLabel}</small></span><b>{reminder.dueOn ?? t("serviceHistory.noDueDate")}</b></header><p>{reminder.customerName} · {reminder.workshopName}</p><div className="quality-contact-links"><a href={`tel:${reminder.customerPhone}`}>{reminder.customerPhone}</a><a href={`mailto:${reminder.customerEmail}`}>{reminder.customerEmail}</a></div>{reminder.lastOutreach && <small>{t("quality.lastContact")}: {t(`quality.channel.${reminder.lastOutreach.channel}` as TranslationKey)} · {reminder.lastOutreach.status}</small>}<form action={action}><input type="hidden" name="recommendationId" value={reminder.id} /><label>{t("quality.channelLabel")}<select name="channel"><option value="phone">{t("quality.channel.phone")}</option><option value="email">{t("quality.channel.email")}</option><option value="in_app">{t("quality.channel.in_app")}</option></select></label><label>{t("quality.phoneOutcome")}<select name="phoneStatus"><option value="contacted">{t("quality.contacted")}</option><option value="not_reached">{t("quality.notReached")}</option></select></label><label>{t("quality.outreachNote")}<input name="note" maxLength={1000} /></label><Result state={state} t={t} /><button disabled={pending}>{t("quality.sendOrRecord")}</button></form></article>;
}

export default function WorkshopQualityClient({ workspace, logoutAction }: { workspace: ManagedQualityWorkspace; logoutAction: () => Promise<void> }) {
  const [language, setLanguage, ready] = useLanguage(); const t = (key: TranslationKey) => translate(language, key);
  const [caseFilter, setCaseFilter] = useState("open");
  const cases = useMemo(() => workspace.cases.filter((item) => caseFilter === "all" || item.status === caseFilter), [workspace.cases, caseFilter]);
  if (!ready) return <main className="registration-shell" aria-busy="true" />;
  return <main className="settings-shell quality-shell"><header className="settings-topbar"><Link href="/workshop-manager">← {t("workspace.back")}</Link><strong>pitster</strong><select value={language} onChange={(event) => setLanguage(event.target.value as Language)} aria-label={t("a11y.languageSelector")}><option value="en">EN</option><option value="de">DE</option><option value="ro">RO</option><option value="hu">HU</option></select><form action={logoutAction}><button>{t("auth.logout")}</button></form></header><section className="settings-content quality-content"><header className="quality-hero"><div><p>{t("quality.eyebrow")}</p><h1>{t("quality.title")}</h1><span>{t("quality.description")}</span></div><dl><div><dt>{t("quality.openCases")}</dt><dd>{workspace.cases.filter((item) => item.status === "open").length}</dd></div><div><dt>{t("quality.dueReminders")}</dt><dd>{workspace.dueReminders.length}</dd></div></dl></header><NewCase workspace={workspace} t={t} /><section className="quality-section"><header><div><p>{t("quality.warrantyEyebrow")}</p><h2>{t("quality.warrantySettings")}</h2></div></header><div className="quality-warranty-list">{workspace.originalJobs.map((job) => <WarrantySettings key={job.id} job={job} t={t} />)}{!workspace.originalJobs.length && <p>{t("quality.noCompletedJobs")}</p>}</div></section><section className="quality-section"><header><div><p>{t("quality.caseListEyebrow")}</p><h2>{t("quality.caseList")}</h2></div><select value={caseFilter} onChange={(event) => setCaseFilter(event.target.value)}><option value="open">{t("quality.status.open")}</option><option value="resolved">{t("quality.status.resolved")}</option><option value="all">{t("common.all")}</option></select></header><div className="quality-case-list">{cases.map((item) => <CaseCard key={item.id} item={item} language={language} t={t} />)}{!cases.length && <p>{t("quality.noCases")}</p>}</div></section><section className="quality-section quality-loyalty"><header><div><p>{t("quality.loyaltyEyebrow")}</p><h2>{t("quality.loyaltyTitle")}</h2><span>{t("quality.loyaltyDescription")}</span></div></header><div className="quality-reminder-list">{workspace.dueReminders.map((reminder) => <Outreach key={reminder.id} reminder={reminder} t={t} />)}{!workspace.dueReminders.length && <p>{t("quality.noDueReminders")}</p>}</div></section></section></main>;
}
